# Pocket Configuration

# running mode
# can be "single", "abtest" and "binlog"
# TODO: add doc link here
mode = "abtest"

# dsn
# running with "single" mode require dsn1
# running with "abtest" or "binlog" mode require dsn1 and dsn2
dsn1 = "root:@tcp(172.17.0.1:33306)/pocket"
dsn2 = "root:@tcp(172.17.0.1:4000)/pocket"

[options]
# clear target database before test
clear-db = true
# running with stable mode, will disable functions like rand() or user()
# this is helpful in abtest
stable = true
# reproduce from log
reproduce = false
# running concurrency
# default value 3
concurrency = 3
# data and log path
path = "/var/log/pocket"
# test duration
duration = "1h"
# check duration
check-duration = "3m"
