sudo: false

dist: focal
language: go
go:
  - 1.13.3

jobs:
  include:
    - name: "tipocket"
      stage: test
      script:
        - make tidy
        - make fmt
        - make lint
        - make test
        - make build
