metadata:
  name: tipocket-ledger-matrix
spec:
  schedule: "0 1 * * *"
  concurrencyPolicy: "Forbid"
  timezone: "Asia/Shanghai"
  startingDeadlineSeconds: 0
  workflowSpec:
    entrypoint: call-tipocket-ledger
    arguments:
      parameters:
        - name: ns
          value: tipocket-ledger-matrix
        - name: purge
          value: "true"
        - name: image-version
          value: release-4.0-nightly
        - name: storage-class
          value: sas
        - name: nemesis
          value: ""
        - name: run-time
          value: "120m"
        - name: loki-addr
          value: "http://gateway.loki.svc"
        - name: loki-username
          value: "loki"
        - name: loki-password
          value: "admin"
        - name: matrix-config
          value: "/config/matrix.yaml"
        - name: matrix-tidb
          value: "tidb.toml"
        - name: matrix-tikv
          value: "tikv.toml"
        - name: matrix-pd
          value: "pd.toml"
        - name: matrix-sql
          value: "mysql-system-vars.sql,tidb-system-vars.sql"
    templates:
      - name: call-tipocket-ledger
        steps:
          - - name: call-wait-cluster
              templateRef:
                name: wait-cluster
                template: wait-cluster
              arguments:
                parameters:
                  - name: ns
                    value: "{{workflow.parameters.ns}}"
          - - name: call-tipocket-ledger
              templateRef:
                name: tipocket-ledger
                template: tipocket-ledger
              arguments:
                parameters:
                  - name: ns
                    value: "{{workflow.parameters.ns}}"
                  - name: purge
                    value: "{{workflow.parameters.purge}}"
                  - name: image-version
                    value: "{{workflow.parameters.image-version}}"
                  - name: storage-class
                    value: "{{workflow.parameters.storage-class}}"
                  - name: nemesis
                    value: "{{workflow.parameters.nemesis}}"
                  - name: run-time
                    value: "{{workflow.parameters.run-time}}"
                  - name: loki-addr
                    value: "{{workflow.parameters.loki-addr}}"
                  - name: loki-username
                    value: "{{workflow.parameters.loki-username}}"
                  - name: loki-password
                    value: "{{workflow.parameters.loki-password}}"
                  - name: matrix-config
                    value: "{{workflow.parameters.matrix-config}}"
                  - name: matrix-tidb
                    value: "{{workflow.parameters.matrix-tidb}}"
                  - name: matrix-tikv
                    value: "{{workflow.parameters.matrix-tikv}}"
                  - name: matrix-pd
                    value: "{{workflow.parameters.matrix-pd}}"
                  - name: matrix-sql
                    value: "{{workflow.parameters.matrix-sql}}"
