[security.encryption]
data-encryption-method = "aes256-ctr"

[security.encryption.master-key]
type = "file"
path = "/var/lib/tikv/master_key"

[security.encryption.previous-master-key]
type = "plaintext"

