[rocksdb.titan]
enabled = true
max-background-gc = 3  # default 1

[rocksdb.defaultcf]
write-buffer-size = "4MB"  # default 128MB
level0-file-num-compaction-trigger = 2  # default 1
max-bytes-for-level-base = "32MB"  # default 512, write-buffer-size * 4
max-bytes-for-level-multiplier = 2


[rocksdb.defaultcf.titan]
min-blob-size = "25KB"  # default 1KB
discardable-ratio = 0.1
