metadata:
  name: tipocket-abtest
  namespace: argo
spec:
  templates:
    - name: tipocket-abtest
      inputs:
        parameters:
          - name: ns
            default: tipocket-abtest
          - name: purge
            default: true
          - name: image_version
          - name: storage_class
          - name: b_version
      container:
        name: tipocket
        image: 'pingcap/tipocket:latest'
        command:
          - sh
          - '-c'
          - |
            /bin/abtest \
            -namespace={{inputs.parameters.ns}} \
            -hub=docker.io \
            -storage-class={{inputs.parameters.storage_class}} \
            -image-version={{inputs.parameters.image_version}} \
            -abtest.image-version={{inputs.parameters.b_version}} \
            -purge={{inputs.parameters.purge}} \
            -client=2 \
            -loki-addr=http://gateway.loki.svc \
            -loki-username=loki \
            -loki-password=admin
      retryStrategy:
        limit: 0
        retryPolicy: Always
