metadata:
  name: tipocket-abtest
  namespace: argo
spec:
  templates:
    - name: tipocket-abtest
      inputs:
        parameters:
          - name: ns
            default: tipocket-abtest
          - name: hub
            default: "docker.io"
          - name: purge
            default: "false"
          - name: repository
            default: pingcap
          - name: image-version
            default: nightly
          - name: abtest_image-version
            value: latest
          - name: storage-class
            default: local-storage
          - name: nemesis
            default: ""
          - name: client
            default: "2"
          - name: run-time
            default: "48h"
          - name: tidb-config
            default: ""
          - name: tikv-config
            default: ""
          - name: pd-config
            default: ""
          - name: abtest_tidb-config
            default: ""
          - name: abtest_tikv-config
            default: ""
          - name: abtest_pd-config
            default: ""
          - name: abtest_concurrency
            default: "3"
          - name: abtest_general-log
            default: "true"
          - name: loki-addr
            default: http://gateway.loki.svc
          - name: loki-username
            default: loki
          - name: loki-password
            default: admin
      outputs:
        artifacts:
          - name: tidb-logs
            archiveLogs: true
            path: /var/run/tipocket-logs
      metadata:
        labels:
          ns: "{{inputs.parameters.ns}}"
      container:
        name: tipocket
        image: 'pingcap/tipocket:latest'
        imagePullPolicy: Always
        command:
          - sh
          - '-c'
          - |
            /bin/abtest \
            -namespace={{inputs.parameters.ns}} \
            -hub={{inputs.parameters.hub}} \
            -storage-class={{inputs.parameters.storage-class}} \
            -repository={{inputs.parameters.repository}} \
            -image-version={{inputs.parameters.image-version}} \
            -abtest.image-version={{inputs.parameters.abtest_image-version}} \
            -purge={{inputs.parameters.purge}} \
            -delNS=true \
            -nemesis={{inputs.parameters.nemesis}} \
            -client={{inputs.parameters.client}} \
            -run-time={{inputs.parameters.run-time}} \
            -tidb-config={{inputs.parameters.tidb-config}} \
            -tikv-config={{inputs.parameters.tikv-config}} \
            -pd-config={{inputs.parameters.pd-config}} \
            -abtest.tidb-config={{inputs.parameters.abtest_tidb-config}} \
            -abtest.tikv-config={{inputs.parameters.abtest_tikv-config}} \
            -abtest.pd-config={{inputs.parameters.abtest_pd-config}} \
            -abtest.concurrency={{inputs.parameters.abtest_concurrency}} \
            -abtest.general-log={{inputs.parameters.abtest_general-log}} \
            -loki-addr={{inputs.parameters.loki-addr}} \
            -loki-username={{inputs.parameters.loki-username}} \
            -loki-password={{inputs.parameters.loki-password}}
