metadata:
  name: tipocket-abtest
  namespace: argo
spec:
  templates:
    - name: tipocket-abtest
      inputs:
        parameters:
          - name: ns
            default: tipocket-abtest
          - name: image_version
            default: latest
          - name: storage_class
            default: pd-ssd
          - name: b_version
            default: nightly
      container:
        name: tipocket
        image: 'pingcap/tipocket:latest'
        command:
          - sh
          - '-c'
          - |
            /bin/abtest \
            -namespace={{inputs.parameters.ns}} \
            -hub=docker.io \
            -storage-class={{inputs.parameters.storage_class}} \
            -image-version={{inputs.parameters.image_version}} \
            -abtest.b.version={{inputs.parameters.b_version}} \
            -purge=true \
            -client=2
      retryStrategy:
        limit: 0
        retryPolicy: Always
