metadata:
  name: tipocket-bank
  namespace: argo
spec:
  templates:
    - name: tipocket-bank
      inputs:
        parameters:
          - name: ns
            default: tipocket-bank
          - name: purge
            default: "false"
          - name: image_version
            default: nightly
          - name: storage_class
            default: standard
          - name: nemesis
            default: "random_kill,kill_pd_leader_5min,partition_one,subcritical_skews,big_skews,shuffle-leader-scheduler,shuffle-region-scheduler,random-merge-scheduler"
          - name: client
            default: "5"
          - name: request_count
            default: "10000"
          - name: round
            default: "100"
          - name: tikv-replicas
            default: "3"
          - name: loki-addr
            default: "http://gateway.loki.svc"
          - name: loki-username
            default: "loki"
          - name: loki-password
            default: "admin"
      container:
        name: tipocket
        image: 'pingcap/tipocket:latest'
        command:
          - sh
          - '-c'
          - |
            /bin/chaos-tidb \
            -namespace={{inputs.parameters.ns}} \
            -hub=docker.io \
            -storage-class={{inputs.parameters.storage_class}} \
            -image-version={{inputs.parameters.image_version}} \
            -purge={{inputs.parameters.purge}} \
            -case=bank \
            -client={{inputs.parameters.client}} \
            -tikv-replicas={{inputs.parameters.tikv-replicas}} \
            -nemesis={{inputs.parameters.nemesis}} \
            -round={{inputs.parameters.round}} \
            -request-count={{inputs.parameters.request_count}} \
            -loki-addr={{inputs.parameters.loki-addr}} \
            -loki-username={{inputs.parameters.loki-username}} \
            -loki-password={{inputs.parameters.loki-password}}
      retryStrategy:
        limit: 0
        retryPolicy: Always
