metadata:
  name: tipocket-binlog
  namespace: argo
spec:
  templates:
    - name: tipocket-binlog
      inputs:
        parameters:
          - name: ns
            default: tipocket-binlog
          - name: hub
            default: "docker.io"
          - name: purge
            default: "false"
          - name: repository
            default: pingcap
          - name: image-version
            default: nightly
          - name: storage-class
            default: local-path
          - name: nemesis
            default: ""
          - name: run-time
            default: "48h"
          - name: relay-log
            default: "true"
          - name: abtest_general-log
            default: "true"
          - name: abtest_concurrency
            default: "3"
          - name: binlog_sync-timeout
            default: "1h"
          - name: loki-addr
            default:
          - name: loki-username
            default: loki
          - name: loki-password
            default: admin
          - name: matrix-config
            default: ""
          - name: matrix-tidb
            default: "tidb.toml"
          - name: matrix-tikv
            default: "tikv.toml"
          - name: matrix-pd
            default: "pd.toml"
          - name: matrix-sql
            default: "mysql-system-vars.sql,tidb-system-vars.sql"
      outputs:
        artifacts:
          - name: tidb-logs
            archiveLogs: true
            path: /var/run/tipocket-logs
      metadata:
        labels:
          ns: "{{inputs.parameters.ns}}"
      container:
        name: tipocket
        image: 'hub.pingcap.net/qa/tipocket:latest'
        imagePullPolicy: Always
        command:
          - sh
          - '-c'
          - |
            /bin/pocket \
            -namespace={{inputs.parameters.ns}} \
            -hub={{inputs.parameters.hub}} \
            -repository={{inputs.parameters.repository}} \
            -storage-class={{inputs.parameters.storage-class}} \
            -image-version={{inputs.parameters.image-version}} \
            -purge={{inputs.parameters.purge}} \
            -delNS=true \
            -nemesis={{inputs.parameters.nemesis}} \
            -run-time={{inputs.parameters.run-time}} \
            -relay-log={{inputs.parameters.relay-log}} \
            -abtest.concurrency={{inputs.parameters.abtest_concurrency}} \
            -abtest.general-log={{inputs.parameters.abtest_general-log}} \
            -binlog.sync-timeout={{inputs.parameters.binlog_sync-timeout}} \
            -loki-addr={{inputs.parameters.loki-addr}} \
            -loki-username={{inputs.parameters.loki-username}} \
            -loki-password={{inputs.parameters.loki-password}} \
            -matrix-config={{inputs.parameters.matrix-config}} \
            -matrix-tidb={{inputs.parameters.matrix-tidb}} \
            -matrix-tikv={{inputs.parameters.matrix-tikv}} \
            -matrix-pd={{inputs.parameters.matrix-pd}} \
            -matrix-sql={{inputs.parameters.matrix-sql}}
