metadata:
  name: tipocket-block-writer
  namespace: argo
spec:
  templates:
    - name: tipocket-block-writer
      inputs:
        parameters:
          - name: ns
            default: tipocket-block-writer
          - name: image_version
          - name: storage_class
      container:
        name: tipocket
        image: 'pingcap/tipocket:latest'
        command:
          - sh
          - '-c'
          - |
            /bin/block-writer \
            -namespace={{inputs.parameters.ns}} \
            -hub=docker.io \
            -storage-class={{inputs.parameters.storage_class}} \
            -image-version={{inputs.parameters.image_version}} \
            -purge=true \
            -run-time=60m \
            -loki-addr=http://gateway.loki.svc \
            -loki-username=loki \
            -loki-password=admin
      retryStrategy:
        limit: 0
        retryPolicy: Always
