metadata:
  name: tipocket-block-writer
  namespace: argo
spec:
  templates:
    - name: tipocket-block-writer
      inputs:
        parameters:
          - name: image_version
      container:
        name: tipocket
        image: 'pingcap/tipocket:latest'
        command:
          - sh
          - '-c'
          - |
            /bin/block-writer \
            -namespace=tipocket-block-writer \
            -hub=docker.io \
            -storage-class={{inputs.parameters.storage_class}} \
            -image-version={{inputs.parameters.image_version}} \
            -purge=true \
            -run-time=60m
      retryStrategy:
        limit: 0
        retryPolicy: Always
