metadata:
  name: tipocket-cdc
  namespace: argo
spec:
  templates:
    - name: tipocket-cdc
      inputs:
        parameters:
          - name: ns
            default: tipocket-cdc
          - name: purge
            default: "false"
          - name: image_version
            default: nightly
          - name: storage_class
            default: standard
          - name: nemesis
            default: ""
          - name: run_time
            default: "48h"
          - name: cdc_hub
            default: docker.io
          - name: cdc_repository
            default: pingcap
          - name: cdc_version
            default: nightly
          - name: cdc_upstream_pd_image
            default: ""
          - name: cdc_upstream_tidb_image
            default: ""
          - name: cdc_upstream_tikv_image
            default: ""
          - name: cdc_downstream_pd_image
            default: ""
          - name: cdc_downstream_tidb_image
            default: ""
          - name: cdc_downstream_tikv_image
            default: ""
          - name: abtest_general_log
            default: "true"
          - name: binlog_sync_timeout
            default: "1h"
          - name: abtest_concurrency
            default: "3"
          - name: loki-addr
            default: http://gateway.loki.svc
          - name: loki-username
            default: loki
          - name: loki-password
            default: admin
      container:
        name: tipocket
        image: 'pingcap/tipocket:latest'
        command:
          - sh
          - '-c'
          - |
            /bin/cdc-pocket \
            -namespace={{inputs.parameters.ns}} \
            -hub=docker.io \
            -storage-class={{inputs.parameters.storage_class}} \
            -image-version={{inputs.parameters.image_version}} \
            -purge={{inputs.parameters.purge}} \
            -nemesis={{inputs.parameters.nemesis}} \
            -run-time={{inputs.parameters.run_time}} \
            -cdc.hub={{inputs.parameters.cdc_hub}} \
            -cdc.repository={{inputs.parameters.cdc_repository}} \
            -cdc.version={{inputs.parameters.cdc_version}} \
            -cdc.upstream.pd-image={{inputs.parameters.cdc_upstream_pd_image}} \
            -cdc.upstream.tidb-image={{inputs.parameters.cdc_upstream_tidb_image}} \
            -cdc.upstream.tikv-image={{inputs.parameters.cdc_upstream_tikv_image}} \
            -cdc.downstream.pd-image={{inputs.parameters.cdc_downstream_pd_image}} \
            -cdc.downstream.tidb-image={{inputs.parameters.cdc_downstream_tidb_image}} \
            -cdc.downstream.tikv-image={{inputs.parameters.cdc_downstream_tikv_image}} \
            -abtest.concurrency={{inputs.parameters.abtest_concurrency}} \
            -abtest.general-log={{inputs.parameters.abtest_general_log}} \
            -binlog.sync-timeout={{inputs.parameters.binlog_sync_timeout}} \
            -loki-addr={{inputs.parameters.loki-addr}} \
            -loki-username={{inputs.parameters.loki-username}} \
            -loki-password={{inputs.parameters.loki-password}}
