metadata:
  name: tipocket-cdc
  namespace: argo
spec:
  templates:
    - name: tipocket-cdc
      inputs:
        parameters:
          - name: ns
            default: tipocket-cdc
          - name: purge
            default: "false"
          - name: repository
            default: pingcap
          - name: image_version
            default: nightly
          - name: tidb_image
            default: ""
          - name: tikv_image
            default: ""
          - name: pd_image
            default: ""
          - name: storage_class
            default: standard
          - name: nemesis
            default: ""
          - name: run_time
            default: "48h"
          - name: tikv_config
            default: ""
          - name: cdc_hub
            default: docker.io
          - name: cdc_repository
            default: pingcap
          - name: cdc_version
            default: nightly
          - name: abtest_general_log
            default: "true"
          - name: binlog_sync_timeout
            default: "1h"
          - name: abtest_concurrency
            default: "3"
          - name: loki-addr
            default: http://gateway.loki.svc
          - name: loki-username
            default: loki
          - name: loki-password
            default: admin
      container:
        name: tipocket
        image: 'pingcap/tipocket:latest'
        command:
          - sh
          - '-c'
          - |
            /bin/cdc-pocket \
            -namespace={{inputs.parameters.ns}} \
            -hub=docker.io \
            -repository={{inputs.parameters.repository}} \
            -storage-class={{inputs.parameters.storage_class}} \
            -image-version={{inputs.parameters.image_version}} \
            -tidb-image={{inputs.parameters.tidb_image}} \
            -tikv-image={{inputs.parameters.tikv_image}} \
            -pd-image={{inputs.parameters.pd_image}} \
            -purge={{inputs.parameters.purge}} \
            -nemesis={{inputs.parameters.nemesis}} \
            -run-time={{inputs.parameters.run_time}} \
            -tikv-config={{inputs.parameters.tikv_config}} \
            -cdc.hub={{inputs.parameters.cdc_hub}} \
            -cdc.repository={{inputs.parameters.cdc_repository}} \
            -cdc.version={{inputs.parameters.cdc_version}} \
            -abtest.concurrency={{inputs.parameters.abtest_concurrency}} \
            -abtest.general-log={{inputs.parameters.abtest_general_log}} \
            -binlog.sync-timeout={{inputs.parameters.binlog_sync_timeout}} \
            -loki-addr={{inputs.parameters.loki-addr}} \
            -loki-username={{inputs.parameters.loki-username}} \
            -loki-password={{inputs.parameters.loki-password}}
