metadata:
  name: tipocket-dm
  namespace: argo
spec:
  templates:
    - name: tipocket-dm
      inputs:
        parameters:
          - name: ns
            default: tipocket-dm
          - name: hub
            default: "docker.io"
          - name: repository
            default: pingcap
          - name: image-version
            default: nightly
          - name: storage-class
            default: local-storage
          - name: nemesis
            default: ""
          - name: run-time
            default: "24h"
          - name: loki-addr
            default: http://gateway.loki.svc
          - name: loki-username
            default: loki
          - name: loki-password
            default: admin
          - name: dm-mysql-version
            default: "5.7"
          - name: dm-mysql-storage-size
            default: "10Gi"
          - name: dm-mysql-enable-binlog
            default: true
          - name: dm-mysql-enable-gtid
            default: true
          - name: dm-version
            default: "nightly"
          - name: dm-master-replicas
            default: 3
          - name: dm-worker-replicas
            default: 3
      outputs:
        artifacts:
          - name: tidb-logs
            archiveLogs: true
            path: /var/run/tipocket-logs
      metadata:
        labels:
          ns: "{{inputs.parameters.ns}}"
      container:
        name: tipocket
        image: 'pingcap/tipocket:latest'
        imagePullPolicy: Always
        command:
          - sh
          - '-c'
          - |
            /bin/dm-pocket \
            -namespace={{inputs.parameters.ns}} \
            -hub={{inputs.parameters.hub}} \
            -repository={{inputs.parameters.repository}} \
            -storage-class={{inputs.parameters.storage-class}} \
            -image-version={{inputs.parameters.image-version}} \
            -nemesis={{inputs.parameters.nemesis}} \
            -run-time={{inputs.parameters.run-time}} \
            -loki-addr={{inputs.parameters.loki-addr}} \
            -loki-username={{inputs.parameters.loki-username}} \
            -loki-password={{inputs.parameters.loki-password}} \
            -dm.mysql.version={{inputs.parameters.dm-mysql-version}} \
            -dm.mysql.storage-size={{inputs.parameters.dm-mysql-storage-size}} \
            -dm.mysql.enable-binlog={{inputs.parameters.dm-mysql-enable-binlog}} \
            -dm.mysql.enable-gtid={{inputs.parameters.dm-mysql-enable-gtid}} \
            -dm.version={{inputs.parameters.dm-version}} \
            -dm.master-replicas={{inputs.parameters.dm-master-replicas}} \
            -dm.worker-replicas={{inputs.parameters.dm-worker-replicas}}
