metadata:
  name: tipocket-follower-read
  namespace: argo
spec:
  templates:
    - name: tipocket-follower-read
      inputs:
        parameters:
          - name: ns
            default: tipocket-follower-read
          - name: hub
            default: "docker.io"
          - name: purge
            default: "true"
          - name: repository
            default: pingcap
          - name: image-version
            default: nightly
          - name: storage-class
            default: local-storage
          - name: nemesis
            default: "random_kill, partition_one, shuffle-leader-scheduler"
          - name: run-time
            default: "6h"
          - name: loki-addr
            default: http://gateway.loki.svc
          - name: loki-username
            default: loki
          - name: loki-password
            default: admin
          - name: tidb-config
            default: ""
          - name: tikv-config
            default: ""
          - name: pd-config
            default: ""
          - name: tikv-replicas
            default: "5"
          - name: enable-follower
            default: "true"
          - name: enable-split
            default: "false"
          - name: seq-loop
            default: "100000"
          - name: insert-num
            default: "100000"
          - name: split-range
            default: "1000000"
      outputs:
        artifacts:
          - name: tidb-logs
            archiveLogs: true
            path: /var/run/tipocket-logs
      metadata:
        labels:
          ns: "{{inputs.parameters.ns}}"
      container:
        name: tipocket
        image: 'pingcap/tipocket:latest'
        command:
          - sh
          - '-c'
          - |
            /bin/follower-read \
            -namespace={{inputs.parameters.ns}} \
            -hub={{inputs.parameters.hub}} \
            -repository={{inputs.parameters.repository}} \
            -storage-class={{inputs.parameters.storage-class}} \
            -image-version={{inputs.parameters.image-version}} \
            -purge={{inputs.parameters.purge}} \
            -tidb-config={{inputs.parameters.tidb-config}} \
            -tikv-config={{inputs.parameters.tikv-config}} \
            -pd-config={{inputs.parameters.pd-config}} \
            -nemesis={{inputs.parameters.nemesis}} \
            -run-time={{inputs.parameters.run-time}} \
            -tikv-replicas={{inputs.parameters.tikv-replicas}} \
            -loki-addr={{inputs.parameters.loki-addr}} \
            -loki-username={{inputs.parameters.loki-username}} \
            -loki-password={{inputs.parameters.loki-password}} \
            -seq-loop={{inputs.parameters.seq-loop}} \
            -insert-num={{inputs.parameters.insert-num}} \
            -split-region-range={{inputs.parameters.split-range}} \
            -enable-follower={{inputs.parameters.enable-follower}} \
            -enable-split={{inputs.parameters.enable-split}}