metadata:
  name: tipocket-gc-in-compaction-filter
  namespace: argo
spec:
  templates:
    - name: tipocket-gc-in-compaction-filter
      inputs:
        parameters:
          - name: ns
            default: tipocket-gc-in-compaction-filter
          - name: purge
            default: "false"
          - name: hub
            default: "docker.io"
          - name: repository
            default: pingcap
          - name: image-version
            default: nightly
          - name: tidb-image
            default: ""
          - name: tikv-image
            default: ""
          - name: pd-image
            default: ""
          - name: storage-class
            default: local-storage
          - name: nemesis
            default: ""
          - name: client
            default: "5"
          - name: request-count
            default: "10000"
          - name: round
            default: "100"
          - name: loki-addr
            default: http://gateway.loki.svc
          - name: loki-username
            default: loki
          - name: loki-password
            default: admin
          - name: tidb-config
            default: ""
          - name: tikv-config
            default: ""
          - name: pd-config
            default: ""
          - name: tikv-replicas
            default: "4"
          - name: matrix-config
            default: ""
          - name: matrix-tidb
            default: "tidb.toml"
          - name: matrix-tikv
            default: "tikv.toml"
          - name: matrix-pd
            default: "pd.toml"
          - name: matrix-sql
            default: "mysql-system-vars.sql,tidb-system-vars.sql"
      outputs:
        artifacts:
          - name: case-logs
            archiveLogs: true
            path: /logs
          - name: tidb-logs
            archiveLogs: true
            path: /var/run/tipocket-logs
      metadata:
        labels:
          ns: "{{inputs.parameters.ns}}"
      container:
        name: tipocket
        image: 'pingcap/tipocket:latest'
        imagePullPolicy: Always
        workingDir: /logs
        command:
          - sh
          - '-c'
          - |
            /bin/gc-in-compaction-filter \
            -namespace={{inputs.parameters.ns}} \
            -hub={{inputs.parameters.hub}} \
            -repository={{inputs.parameters.repository}} \
            -storage-class={{inputs.parameters.storage-class}} \
            -image-version={{inputs.parameters.image-version}} \
            -tidb-image={{inputs.parameters.tidb-image}} \
            -tikv-image={{inputs.parameters.tikv-image}} \
            -pd-image={{inputs.parameters.pd-image}} \
            -purge={{inputs.parameters.purge}} \
            -delNS=true \
            -case=bank \
            -client={{inputs.parameters.client}} \
            -tidb-config={{inputs.parameters.tidb-config}} \
            -tikv-config={{inputs.parameters.tikv-config}} \
            -pd-config={{inputs.parameters.pd-config}} \
            -tikv-replicas={{inputs.parameters.tikv-replicas}} \
            -nemesis={{inputs.parameters.nemesis}} \
            -round={{inputs.parameters.round}} \
            -request-count={{inputs.parameters.request-count}} \
            -loki-addr={{inputs.parameters.loki-addr}} \
            -loki-username={{inputs.parameters.loki-username}} \
            -loki-password={{inputs.parameters.loki-password}} \
            -matrix-config={{inputs.parameters.matrix-config}} \
            -matrix-tidb={{inputs.parameters.matrix-tidb}} \
            -matrix-tikv={{inputs.parameters.matrix-tikv}} \
            -matrix-pd={{inputs.parameters.matrix-pd}} \
            -matrix-sql={{inputs.parameters.matrix-sql}} \
            -wait-safe-point
