metadata:
  name: tipocket-ledger
  namespace: argo
spec:
  templates:
    - name: tipocket-ledger
      inputs:
        parameters:
          - name: ns
            default: tipocket-ledger
          - name: purge
            default: "false"
          - name: image_version
            default: nightly
          - name: storage_class
            default: standard
          - name: nemesis
            default: ""
          - name: run_time
            default: "60m"
          - name: loki-addr
            default: http://gateway.loki.svc
          - name: loki-username
            default: loki
          - name: loki-password
            default: admin
      container:
        name: tipocket
        image: 'pingcap/tipocket:latest'
        command:
          - sh
          - '-c'
          - |
            /bin/ledger \
            -namespace={{inputs.parameters.ns}} \
            -hub=docker.io \
            -storage-class={{inputs.parameters.storage_class}} \
            -image-version={{inputs.parameters.image_version}} \
            -purge={{inputs.parameters.purge}} \
            -nemesis={{inputs.parameters.nemesis}} \
            -run-time={{inputs.parameters.run_time}} \
            -loki-addr={{inputs.parameters.loki-addr}} \
            -loki-username={{inputs.parameters.loki-username}} \
            -loki-password={{inputs.parameters.loki-password}}
