metadata:
  name: tipocket-ledger
  namespace: argo
spec:
  templates:
    - name: tipocket-ledger
      inputs:
        parameters:
          - name: image_version
          - name: storage_class
      container:
        name: tipocket
        image: 'pingcap/tipocket:latest'
        command:
          - sh
          - '-c'
          - |
            /bin/ledger \
            -namespace=tipocket-ledger \
            -hub=docker.io \
            -storage-class={{inputs.parameters.storage_class}} \
            -image-version={{inputs.parameters.image_version}} \
            -purge=true \
            -nemesis=random_kill,short_kill_tikv_1node,short_kill_pd_leader,kill_tikv_1node_5min \
            -run-time=60m
      retryStrategy:
        limit: 0
        retryPolicy: Always
