metadata:
  name: tipocket-ledger
  namespace: argo
spec:
  templates:
    - name: tipocket-ledger
      inputs:
        parameters:
          - name: ns
            default: tipocket-ledger
          - name: purge
            default: true
          - name: image_version
          - name: storage_class
      container:
        name: tipocket
        image: 'pingcap/tipocket:latest'
        command:
          - sh
          - '-c'
          - |
            /bin/ledger \
            -namespace={{inputs.parameters.ns}} \
            -hub=docker.io \
            -storage-class={{inputs.parameters.storage_class}} \
            -image-version={{inputs.parameters.image_version}} \
            -purge={{inputs.parameters.purge}} \
            -nemesis=random_kill,short_kill_tikv_1node,short_kill_pd_leader,kill_tikv_1node_5min \
            -run-time=60m \
            -loki-addr=http://gateway.loki.svc \
            -loki-username=loki \
            -loki-password=admin
      retryStrategy:
        limit: 0
        retryPolicy: Always
