metadata:
  name: tipocket-list-append
  namespace: argo
spec:
  templates:
    - name: tipocket-list-append
      inputs:
        parameters:
          - name: table-count
            default: 7
          - name: read-lock
            default: "\"FOR UPDATE\""
          - name: txn-mode
            default: pessimistic
          - name: ns
            default: tipocket-list-append
          - name: hub
            default: "docker.io"
          - name: purge
            default: "false"
          - name: repository
            default: pingcap
          - name: image-version
            default: nightly
          - name: tidb-image
            default: ""
          - name: tikv-image
            default: ""
          - name: pd-image
            default: ""
          - name: storage-class
            default: local-storage
          - name: nemesis
            default: "random_kill,kill_pd_leader_5min,partition_one,subcritical_skews,big_skews,shuffle-leader-scheduler,shuffle-region-scheduler,random-merge-scheduler"
          - name: client
            default: "5"
          - name: request-count
            default: "10000"
          - name: round
            default: "1"
          - name: loki-addr
            default: http://gateway.loki.svc
          - name: loki-username
            default: loki
          - name: loki-password
            default: admin
          - name: tidb-config
            default: ""
          - name: tikv-config
            default: ""
          - name: pd-config
            default: ""
          - name: tikv-replicas
            default: "4"
          - name: matrix-config
            default: "/config/matrix.yaml"
          - name: matrix-tidb
            default: "tidb.toml"
          - name: matrix-tikv
            default: "tikv.toml"
          - name: matrix-pd
            default: "pd.toml"
          - name: matrix-sql
            default: "mysql-system-vars.sql;tidb-system-vars.sql"
      outputs:
        artifacts:
          - name: case-logs
            archiveLogs: true
            path: /logs
          - name: tidb-logs
            archiveLogs: true
            path: /var/run/tipocket-logs
      metadata:
        labels:
          ns: "{{inputs.parameters.ns}}"
      container:
        name: tipocket
        image: 'pingcap/tipocket:latest'
        imagePullPolicy: Always
        workingDir: /logs
        command:
          - sh
          - '-c'
          - |
            /bin/append \
            -table-count={{inputs.parameters.table-count}} \
            -read-lock={{inputs.parameters.read-lock}} \
            -txn-mode={{inputs.parameters.txn-mode}} \
            -namespace={{inputs.parameters.ns}} \
            -hub={{inputs.parameters.hub}} \
            -repository={{inputs.parameters.repository}} \
            -storage-class={{inputs.parameters.storage-class}} \
            -image-version={{inputs.parameters.image-version}} \
            -tidb-image={{inputs.parameters.tidb-image}} \
            -tikv-image={{inputs.parameters.tikv-image}} \
            -pd-image={{inputs.parameters.pd-image}} \
            -tidb-config={{inputs.parameters.tidb-config}} \
            -tikv-config={{inputs.parameters.tikv-config}} \
            -pd-config={{inputs.parameters.pd-config}} \
            -purge={{inputs.parameters.purge}} \
            -delNS=true \
            -client={{inputs.parameters.client}} \
            -tikv-replicas={{inputs.parameters.tikv-replicas}} \
            -nemesis={{inputs.parameters.nemesis}} \
            -round={{inputs.parameters.round}} \
            -request-count={{inputs.parameters.request-count}} \
            -loki-addr={{inputs.parameters.loki-addr}} \
            -loki-username={{inputs.parameters.loki-username}} \
            -loki-password={{inputs.parameters.loki-password}} \
            -matrix-config={{inputs.parameters.matrix-config}} \
            -matrix-tidb={{inputs.parameters.matrix-tidb}} \
            -matrix-tikv={{inputs.parameters.matrix-tikv}} \
            -matrix-pd={{inputs.parameters.matrix-pd}} \
            -matrix-sql={{inputs.parameters.matrix-sql}}
