metadata:
  name: tipocket-read-stress
  namespace: argo
spec:
  templates:
    - name: tipocket-read-stress
      inputs:
        parameters:
          - name: ns
            default: tipocket-read-stress
          - name: hub
            default: "docker.io"
          - name: purge
            default: "true"
          - name: repository
            default: pingcap
          - name: image-version
            default: nightly
          - name: storage-class
            default: local-path
          - name: nemesis
            default: "random_kill, partition_one, shuffle-leader-scheduler"
          - name: run-time
            default: "6h"
          - name: tikv-config
            default: ""
          - name: loki-addr
            default:
          - name: loki-username
            default: loki
          - name: loki-password
            default: admin
          - name: tikv-replicas
            default: "4"
          - name: tidb-replica-read
            default: "leader"
          - name: matrix-config
            default: ""
          - name: matrix-tidb
            default: "tidb.toml"
          - name: matrix-tikv
            default: "tikv.toml"
          - name: matrix-pd
            default: "pd.toml"
          - name: matrix-sql
            default: "mysql-system-vars.sql,tidb-system-vars.sql"
      outputs:
        artifacts:
          - name: tidb-logs
            archiveLogs: true
            path: /var/run/tipocket-logs
      metadata:
        labels:
          ns: "{{inputs.parameters.ns}}"
      container:
        name: tipocket
        image: 'hub.pingcap.net/qa/tipocket:latest'
        command:
          - sh
          - '-c'
          - |
            /bin/read-stress \
            -namespace={{inputs.parameters.ns}} \
            -hub={{inputs.parameters.hub}} \
            -repository={{inputs.parameters.repository}} \
            -storage-class={{inputs.parameters.storage-class}} \
            -image-version={{inputs.parameters.image-version}} \
            -purge={{inputs.parameters.purge}} \
            -delNS=true \
            -nemesis={{inputs.parameters.nemesis}} \
            -run-time={{inputs.parameters.run-time}} \
            -tikv-replicas={{inputs.parameters.tikv-replicas}} \
            -tikv-config={{inputs.parameters.tikv-config}} \
            -loki-addr={{inputs.parameters.loki-addr}} \
            -loki-username={{inputs.parameters.loki-username}} \
            -loki-password={{inputs.parameters.loki-password}} \
            -tidb-replica-read={{inputs.parameters.tidb-replica-read}} \
            -matrix-config={{inputs.parameters.matrix-config}} \
            -matrix-tidb={{inputs.parameters.matrix-tidb}} \
            -matrix-tikv={{inputs.parameters.matrix-tikv}} \
            -matrix-pd={{inputs.parameters.matrix-pd}} \
            -matrix-sql={{inputs.parameters.matrix-sql}}