metadata:
  name: tipocket-read-stress
  namespace: argo
spec:
  templates:
    - name: tipocket-read-stress
      inputs:
        parameters:
          - name: ns
            default: tipocket-read-stress
          - name: purge
            default: "true"
          - name: repository
            default: pingcap
          - name: image_version
            default: nightly
          - name: storage_class
            default: standard
          - name: nemesis
            default: ""
          - name: run_time
            default: "6h"
          - name: tikv_config
            default: ""
          - name: loki-addr
            default: http://gateway.loki.svc
          - name: loki-username
            default: loki
          - name: loki-password
            default: admin
          - name: tikv-replicas
            default: "4"
      outputs:
        artifacts:
          - name: tidb-logs
            archiveLogs: true
            path: /var/run/tipocket-logs
      metadata:
        labels:
          ns: "{{inputs.parameters.ns}}"
      container:
        name: tipocket
        image: 'pingcap/tipocket:latest'
        command:
          - sh
          - '-c'
          - |
            /bin/read-stress \
            -namespace={{inputs.parameters.ns}} \
            -hub=docker.io \
            -repository={{inputs.parameters.repository}} \
            -storage-class={{inputs.parameters.storage_class}} \
            -image-version={{inputs.parameters.image_version}} \
            -purge={{inputs.parameters.purge}} \
            -nemesis={{inputs.parameters.nemesis}} \
            -run-time={{inputs.parameters.run_time}} \
            -tikv-replicas={{inputs.parameters.tikv-replicas}} \
            -tikv-config={{inputs.parameters.tikv_config}} \
            -loki-addr={{inputs.parameters.loki-addr}} \
            -loki-username={{inputs.parameters.loki-username}} \
            -loki-password={{inputs.parameters.loki-password}}
