metadata:
  name: tipocket-scbank2
  namespace: argo
spec:
  templates:
    - name: tipocket-scbank2
      inputs:
        parameters:
          - name: ns
            default: tipocket-scbank2
          - name: purge
            default: "false"
          - name: hub
            default: "docker.io"
          - name: repository
            default: pingcap
          - name: image-version
            default: nightly
          - name: tidb-image
            default: ""
          - name: tikv-image
            default: ""
          - name: pd-image
            default: ""
          - name: storage-class
            default: local-path
          - name: run-time
            default: "5h"
          - name: nemesis
            default: "random_kill,kill_pd_leader_5min,partition_one,subcritical_skews,big_skews,shuffle-leader-scheduler,shuffle-region-scheduler,random-merge-scheduler"
          - name: loki-addr
            default:
          - name: loki-username
            default: loki
          - name: loki-password
            default: admin
          - name: tidb-config
            default: ""
          - name: tikv-config
            default: ""
          - name: pd-config
            default: ""
          - name: tikv-replicas
            default: "3"
          - name: tidb-replica-read
            default: "leader"
          - name: matrix-config
            default: ""
          - name: matrix-tidb
            default: "tidb.toml"
          - name: matrix-tikv
            default: "tikv.toml"
          - name: matrix-pd
            default: "pd.toml"
          - name: matrix-sql
            default: "mysql-system-vars.sql,tidb-system-vars.sql"
          - name: concurrency
            default: "200"
          - name: accounts
            default: "1000000"
          - name: tidb-failpoint
            default: "\"github.com/pingcap/tidb/server/enableTestAPI=return\""
          - name: async-commit
            default: "false"
          - name: one-pc
            default: "false"
      outputs:
        artifacts:
          - name: tidb-logs
            archiveLogs: true
            path: /var/run/tipocket-logs
      metadata:
        labels:
          ns: "{{inputs.parameters.ns}}"
      container:
        name: tipocket
        image: 'pingcap/tipocket:latest'
        imagePullPolicy: Always
        command:
          - sh
          - '-c'
          - |
            /bin/bank2 \
            -namespace={{inputs.parameters.ns}} \
            -hub={{inputs.parameters.hub}} \
            -repository={{inputs.parameters.repository}} \
            -storage-class={{inputs.parameters.storage-class}} \
            -run-time={{inputs.parameters.run-time}} \
            -image-version={{inputs.parameters.image-version}} \
            -tidb-image={{inputs.parameters.tidb-image}} \
            -tikv-image={{inputs.parameters.tikv-image}} \
            -pd-image={{inputs.parameters.pd-image}} \
            -purge={{inputs.parameters.purge}} \
            -delNS=true \
            -tidb-config={{inputs.parameters.tidb-config}} \
            -tikv-config={{inputs.parameters.tikv-config}} \
            -pd-config={{inputs.parameters.pd-config}} \
            -nemesis={{inputs.parameters.nemesis}} \
            -tikv-replicas={{inputs.parameters.tikv-replicas}} \
            -loki-addr={{inputs.parameters.loki-addr}} \
            -loki-username={{inputs.parameters.loki-username}} \
            -loki-password={{inputs.parameters.loki-password}} \
            -tidb-replica-read={{inputs.parameters.tidb-replica-read}} \
            -plugin.leak.eat=http://pingcap-dev.hk.ufileos.com/schrodinger/eat.txt \
            -matrix-config={{inputs.parameters.matrix-config}} \
            -matrix-tidb={{inputs.parameters.matrix-tidb}} \
            -matrix-tikv={{inputs.parameters.matrix-tikv}} \
            -matrix-pd={{inputs.parameters.matrix-pd}} \
            -matrix-sql={{inputs.parameters.matrix-sql}} \
            -concurrency={{inputs.parameters.concurrency}} \
            -accounts={{inputs.parameters.accounts}} \
            -failpoint.tidb={{inputs.parameters.tidb-failpoint}} \
            -async-commit={{inputs.parameters.async-commit}} \
            -one-pc={{inputs.parameters.one-pc}}
