metadata:
  name: tipocket-scbank
  namespace: argo
spec:
  templates:
    - name: tipocket-scbank
      inputs:
        parameters:
          - name: ns
            default: tipocket-scbank
          - name: hub
            default: "docker.io"
          - name: purge
            default: "false"
          - name: image-version
            default: nightly
          - name: repository
            default: pingcap
          - name: storage-class
            default: standard
          - name: run-time
            default: "5h"
          - name: nemesis
            default: "random_kill,kill_pd_leader_5min,partition_one,subcritical_skews,big_skews,shuffle-leader-scheduler,shuffle-region-scheduler,random-merge-scheduler"
          - name: loki-addr
            default: http://gateway.loki.svc
          - name: loki-username
            default: loki
          - name: loki-password
            default: admin
          - name: tidb-config
            default: ""
          - name: tikv-config
            default: ""
          - name: pd-config
            default: ""
          - name: tikv-replicas
            default: "3"
          - name: tidb-replica-read
            default: "leader"
      outputs:
        artifacts:
          - name: tidb-logs
            archiveLogs: true
            path: /var/run/tipocket-logs
      metadata:
        labels:
          ns: "{{inputs.parameters.ns}}"
      container:
        name: tipocket
        image: 'pingcap/tipocket:latest'
        imagePullPolicy: Always
        command:
          - sh
          - '-c'
          - |
            /bin/bank \
            -namespace={{inputs.parameters.ns}} \
            -hub={{inputs.parameters.hub}} \
            -repository={{inputs.parameters.repository}} \
            -storage-class={{inputs.parameters.storage-class}} \
            -run-time={{inputs.parameters.run-time}} \
            -image-version={{inputs.parameters.image-version}} \
            -purge={{inputs.parameters.purge}} \
            -tidb-config={{inputs.parameters.tidb-config}} \
            -tikv-config={{inputs.parameters.tikv-config}} \
            -pd-config={{inputs.parameters.pd-config}} \
            -nemesis={{inputs.parameters.nemesis}} \
            -tikv-replicas={{inputs.parameters.tikv-replicas}} \
            -loki-addr={{inputs.parameters.loki-addr}} \
            -loki-username={{inputs.parameters.loki-username}} \
            -loki-password={{inputs.parameters.loki-password}} \
            -tidb-replica-read={{inputs.parameters.tidb-replica-read}}
