metadata:
  name: tipocket-sqllogic
  namespace: argo
spec:
  templates:
    - name: tipocket-sqllogic
      inputs:
        parameters:
          - name: ns
            default: tipocket-sqllogic
          - name: purge
            default: "false"
          - name: hub
            default: "docker.io"
          - name: repository
            default: pingcap
          - name: image-version
            default: nightly
          - name: tidb-image
            default: ""
          - name: tikv-image
            default: ""
          - name: pd-image
            default: ""
          - name: storage-class
            default: local-path
          - name: run-time
            default: "8h"
          - name: loki-addr
            default:
          - name: loki-username
            default: loki
          - name: loki-password
            default: admin
          - name: tidb-replica-read
            default: "leader"
          - name: case-addr
            default: "https://github.com/mahjonp/sqllogictest/archive/tipocket.tar.gz"
          - name: case-dir
            default: "sqllogictest-tipocket"
          - name: matrix-config
            default: ""
          - name: matrix-tidb
            default: "tidb.toml"
          - name: matrix-tikv
            default: "tikv.toml"
          - name: matrix-pd
            default: "pd.toml"
          - name: matrix-sql
            default: "mysql-system-vars.sql,tidb-system-vars.sql"
      outputs:
        artifacts:
          - name: tidb-logs
            archiveLogs: true
            path: /var/run/tipocket-logs
      metadata:
        labels:
          ns: "{{inputs.parameters.ns}}"
      container:
        name: tipocket
        image: 'hub.pingcap.net/qa/tipocket:latest'
        imagePullPolicy: Always
        command:
          - sh
          - '-c'
          - |
            /bin/sqllogic \
            -namespace={{inputs.parameters.ns}} \
            -hub={{inputs.parameters.hub}} \
            -repository={{inputs.parameters.repository}} \
            -storage-class={{inputs.parameters.storage-class}} \
            -image-version={{inputs.parameters.image-version}} \
            -tidb-image={{inputs.parameters.tidb-image}} \
            -tikv-image={{inputs.parameters.tikv-image}} \
            -pd-image={{inputs.parameters.pd-image}} \
            -purge={{inputs.parameters.purge}} \
            -delNS=true \
            -run-time={{inputs.parameters.run-time}} \
            -p={{inputs.parameters.case-addr}} \
            -d={{inputs.parameters.case-dir}} \
            -loki-addr={{inputs.parameters.loki-addr}} \
            -loki-username={{inputs.parameters.loki-username}} \
            -loki-password={{inputs.parameters.loki-password}} \
            -tidb-replica-read={{inputs.parameters.tidb-replica-read}} \
            -matrix-config={{inputs.parameters.matrix-config}} \
            -matrix-tidb={{inputs.parameters.matrix-tidb}} \
            -matrix-tikv={{inputs.parameters.matrix-tikv}} \
            -matrix-pd={{inputs.parameters.matrix-pd}} \
            -matrix-sql={{inputs.parameters.matrix-sql}}