metadata:
  name: tipocket-sqllogic
  namespace: argo
spec:
  templates:
    - name: tipocket-sqllogic
      inputs:
        parameters:
          - name: ns
            default: tipocket-sqllogic
          - name: purge
            default: "false"
          - name: image_version
            default: nightly
          - name: storage_class
            default: standard
          - name: loki-addr
            default: http://gateway.loki.svc
          - name: loki-username
            default: loki
          - name: loki-password
            default: admin
      container:
        name: tipocket
        image: 'pingcap/tipocket:latest'
        command:
          - sh
          - '-c'
          - |
            /bin/sqllogic \
            -namespace={{inputs.parameters.ns}} \
            -hub=docker.io \
            -storage-class={{inputs.parameters.storage_class}} \
            -image-version={{inputs.parameters.image_version}} \
            -purge={{inputs.parameters.purge}} \
            -run-time=8h \
            -p=https://codeload.github.com/mahjonp/sqllogictest/zip/tipocket \
            -d=sqllogictest-tipocket \
            -loki-addr={{inputs.parameters.loki-addr}} \
            -loki-username={{inputs.parameters.loki-username}} \
            -loki-password={{inputs.parameters.loki-password}}
