metadata:
  name: tipocket-tiflash
  namespace: argo
spec:
  templates:
    - name: tipocket-tiflash
      inputs:
        parameters:
          - name: ns
            default: tipocket-tiflash
          - name: purge
            default: "false"
          - name: image_version
            default: nightly
          - name: storage_class
            default: standard
          - name: nemesis
            default: ""
          - name: tiflash_image
            default: "pingcap/tiflash:release-4.0"
          - name: tiflash_replicas
            default: 1
          - name: run_time
            default: "48h"
          - name: tikv_config
            default: "/config/tiflash/tikv.toml"
          - name: pd_config
            default: "/config/tiflash/pd.toml"
          - name: loki-addr
            default: http://gateway.loki.svc
          - name: loki-username
            default: loki
          - name: loki-password
            default: admin
      container:
        name: tipocket
        image: 'yeya24/tipocket:tiflash'
        command:
          - sh
          - '-c'
          - |
            /bin/tiflash-pocket \
            -namespace={{inputs.parameters.ns}} \
            -hub=docker.io \
            -storage-class={{inputs.parameters.storage_class}} \
            -image-version={{inputs.parameters.image_version}} \
            -purge={{inputs.parameters.purge}} \
            -nemesis={{inputs.parameters.nemesis}} \
            -run-time={{inputs.parameters.run_time}} \
            -tikv-config={{inputs.parameters.tikv_config}} \
            -pd-config={{inputs.parameters.pd_config}} \
            -tiflash.replica={{inputs.parameters.tiflash_replicas}} \
            -tiflash.image={{inputs.parameters.tiflash_image}} \
            -loki-addr={{inputs.parameters.loki-addr}} \
            -loki-username={{inputs.parameters.loki-username}} \
            -loki-password={{inputs.parameters.loki-password}}
