metadata:
  name: tipocket-tiflash
  namespace: argo
spec:
  templates:
    - name: tipocket-tiflash
      inputs:
        parameters:
          - name: ns
            default: tipocket-tiflash
          - name: hub
            default: "docker.io"
          - name: purge
            default: "false"
          - name: repository
            default: pingcap
          - name: image-version
            default: nightly
          - name: storage-class
            default: standard
          - name: nemesis
            default: ""
          - name: tiflash-image
            default: ""
          - name: tiflash-replicas
            default: 2
          - name: run-time
            default: "48h"
          - name: loki-addr
            default: http://gateway.loki.svc
          - name: loki-username
            default: loki
          - name: loki-password
            default: admin
      outputs:
        artifacts:
          - name: tidb-logs
            archiveLogs: true
            path: /var/run/tipocket-logs
      metadata:
        labels:
          ns: "{{inputs.parameters.ns}}"
      container:
        name: tipocket
        image: 'pingcap/tipocket:latest'
        imagePullPolicy: Always
        command:
          - sh
          - '-c'
          - |
            /bin/tiflash-pocket \
            -namespace={{inputs.parameters.ns}} \
            -hub={{inputs.parameters.hub}} \
            -repository={{inputs.parameters.repository}} \
            -storage-class={{inputs.parameters.storage-class}} \
            -image-version={{inputs.parameters.image-version}} \
            -purge={{inputs.parameters.purge}} \
            -nemesis={{inputs.parameters.nemesis}} \
            -run-time={{inputs.parameters.run-time}} \
            -tiflash-replicas={{inputs.parameters.tiflash-replicas}} \
            -tiflash-image={{inputs.parameters.tiflash-image}} \
            -loki-addr={{inputs.parameters.loki-addr}} \
            -loki-username={{inputs.parameters.loki-username}} \
            -loki-password={{inputs.parameters.loki-password}}
