metadata:
  name: tipocket-tpcc
  namespace: argo
spec:
  templates:
    - name: tipocket-tpcc
      inputs:
        parameters:
          - name: image_version
          - name: storage_class
      container:
        name: tipocket
        image: 'pingcap/tipocket:latest'
        command:
          - sh
          - '-c'
          - |
            /bin/tpcc \
            -namespace=tipocket-tpcc-test \
            -hub=docker.io \
            -storage-class=local-scsi \
            -storage-class={{inputs.parameters.storage_class}} \
            -image-version={{inputs.parameters.image_version}} \
            -purge=true \
            -client=100 \
            -nemesis=random_kill,short_kill_tikv_1node,short_kill_pd_leader,kill_tikv_1node_5min \
            -round=5 \
            -request-count=100000
      retryStrategy:
        limit: 0
        retryPolicy: Always