metadata:
  name: tipocket-tpcc
  namespace: argo
spec:
  templates:
    - name: tipocket-tpcc
      inputs:
        parameters:
          - name: ns
            default: tipocket-tpcc
          - name: hub
            default: "docker.io"
          - name: purge
            default: "false"
          - name: repository
            default: pingcap
          - name: image_version
            default: nightly
          - name: storage_class
            default: standard
          - name: client
            default: "100"
          - name: request_count
            default: "1000000"
          - name: round
            default: "10"
          - name: nemesis
            default: ""
          - name: loki-addr
            default: http://gateway.loki.svc
          - name: loki-username
            default: loki
          - name: loki-password
            default: admin
      outputs:
        artifacts:
          - name: tidb-logs
            archiveLogs: true
            path: /var/run/tipocket-logs
      metadata:
        labels:
          ns: "{{inputs.parameters.ns}}"
      container:
        name: tipocket
        image: 'pingcap/tipocket:latest'
        imagePullPolicy: Always
        command:
          - sh
          - '-c'
          - |
            /bin/tpcc \
            -namespace={{inputs.parameters.ns}} \
            -hub={{inputs.parameters.hub}} \
            -repository={{inputs.parameters.repository}} \
            -storage-class={{inputs.parameters.storage_class}} \
            -image-version={{inputs.parameters.image_version}} \
            -purge={{inputs.parameters.purge}} \
            -client={{inputs.parameters.client}} \
            -nemesis={{inputs.parameters.nemesis}} \
            -round={{inputs.parameters.round}} \
            -request-count={{inputs.parameters.request_count}} \
            -loki-addr={{inputs.parameters.loki-addr}} \
            -loki-username={{inputs.parameters.loki-username}} \
            -loki-password={{inputs.parameters.loki-password}}
