apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: tipocket-list-append-
spec:
  entrypoint: starter
  onExit: delete-ns
  templates:
    - name: starter
      steps:
        - - name: create-ns
            template: create-ns
        - - name: run-tipocket
            template: run-tipocket
    - container:
        command:
          - sh
          - -c
          - |-
            /bin/append \
            -table-count=7 \
            -read-lock="FOR UPDATE" \
            -txn-mode=pessimistic \
            -client=1 \
            -delete_ns=false \
            -hub=docker.io \
            -image_version=nightly \
            -namespace={{workflow.name}} \
            -nemesis=random_kill,kill_pd_leader_5min,partition_one,subcritical_skews,big_skews,shuffle-leader-scheduler,shuffle-region-scheduler,random-merge-scheduler \
            -pd_config= \
            -pd_image= \
            -purge=false \
            -repository=pingcap \
            -request_count=10000 \
            -round=1 \
            -storage_class=local-path \
            -tidb_config= \
            -tidb_image= \
            -tikv_config= \
            -tikv_image=
        image: hub.pingcap.net/qa/tipocket
        imagePullPolicy: Always
        name: tipocket
        workingDir: /logs
      name: run-tipocket
      outputs:
        artifacts:
          - archiveLogs: true
            name: case-logs
            path: path
          - archiveLogs: true
            name: tidb-logs
            path: /var/run/tipocket-logs
    - name: create-ns
      resource:
        action: create
        manifest: |
          apiVersion: v1
          kind: Namespace
          metadata:
            name: {{workflow.name}}
        successCondition: status.phase = Active
    - name: delete-ns
      resource:
        action: delete
        manifest: |
          apiVersion: v1
          kind: Namespace
          metadata:
            name: {{workflow.name}}
