# The maximum memory available for a single SQL statement. Default: 1GB, use 100M here
mem-quota-query = 107374182

# Controls whether to enable the temporary storage for some operators when a single SQL statement exceeds the memory quota specified by mem-quota-query.
oom-use-tmp-storage = true
