metadata:
  name: tipocket-bank
spec:
  schedule: "0 0 * * *"
  concurrencyPolicy: "Forbid"
  timezone: "Asia/Shanghai"
  startingDeadlineSeconds: 0
  workflowSpec:
    entrypoint: call-tipocket-bank
    arguments:
      parameters:
        - name: ns
          value: tipocket-bank
        - name: purge
          value: "true"
        - name: image_version
          value: release-4.0-nightly
        - name: storage_class
          value: gp2
        - name: nemesis
          value: random_kill,kill_pd_leader_5min,partition_one,subcritical_skews,big_skews,shuffle-leader-scheduler,shuffle-region-scheduler,random-merge-scheduler
        - name: client
          value: "5"
        - name: request_count
          value: "20000"
        - name: round
          value: "100"
    templates:
      - name: call-tipocket-bank
        steps:
          - - name: call-tipocket-bank
              templateRef:
                name: tipocket-bank
                template: tipocket-bank
              arguments:
                parameters:
                  - name: ns
                    value: "{{workflow.parameters.ns}}"
                  - name: purge
                    value: "{{workflow.parameters.purge}}"
                  - name: image_version
                    value: "{{workflow.parameters.image_version}}"
                  - name: storage_class
                    value: "{{workflow.parameters.storage_class}}"
                  - name: nemesis
                    value: "{{workflow.parameters.nemesis}}"
                  - name: client
                    value: "{{workflow.parameters.client}}"
                  - name: request_count
                    value: "{{workflow.parameters.request_count}}"
                  - name: round
                    value: "{{workflow.parameters.round}}"
