metadata:
  name: tipocket-cdc-kafka-normal
spec:
  schedule: "0 */6 * * *"
  concurrencyPolicy: "Forbid"
  timezone: "Asia/Shanghai"
  startingDeadlineSeconds: 0
  workflowSpec:
    entrypoint: call-tipocket-cdc
    arguments:
      parameters:
        - name: ns
          value: tipocket-cdc-kafka-normal
        - name: purge
          value: "true"
        - name: hub
          value: "docker.io"
        - name: repository
          value: "pingcap"
        - name: image-version
          value: nightly
        - name: tidb-image
          value: ""
        - name: tikv-image
          value: "c3219bb"
        - name: pd-image
          value: ""
        - name: storage-class
          value: local-storage
        - name: nemesis
          value: ""
        - name: run-time
          value: "12h"
        - name: tikv-config
          value: ""
        - name: cdc_hub
          value: "docker.io"
        - name: cdc_repository
          value: "pingcap"
        - name: cdc_version
          value: "master"
        - name: cdc_enable-kafka
          value: "true"
        - name: cdc_kafka-consumer-image
          value: "docker.io/pingcap/ticdc-kafka:nightly"
        - name: abtest_general-log
          value: "true"
        - name: binlog_sync-timeout
          value: "30m"
        - name: abtest_concurrency
          value: "3"
        - name: loki-addr
          value: "http://gateway.loki.svc"
        - name: loki-username
          value: "loki"
        - name: loki-password
          value: "admin"
    templates:
      - name: call-tipocket-cdc
        steps:
          - - name: call-wait-cluster
              templateRef:
                name: wait-cluster
                template: wait-cluster
              arguments:
                parameters:
                  - name: ns
                    value: "{{workflow.parameters.ns}}"
          - - name: call-tipocket-cdc
              templateRef:
                name: tipocket-cdc
                template: tipocket-cdc
              arguments:
                parameters:
                  - name: ns
                    value: "{{workflow.parameters.ns}}"
                  - name: purge
                    value: "{{workflow.parameters.purge}}"
                  - name: hub
                    value: "{{workflow.parameters.hub}}"
                  - name: repository
                    value: "{{workflow.parameters.repository}}"
                  - name: image-version
                    value: "{{workflow.parameters.image-version}}"
                  - name: tidb-image
                    value: "{{workflow.parameters.tidb-image}}"
                  - name: tikv-image
                    value: "{{workflow.parameters.tikv-image}}"
                  - name: pd-image
                    value: "{{workflow.parameters.pd-image}}"
                  - name: storage-class
                    value: "{{workflow.parameters.storage-class}}"
                  - name: nemesis
                    value: "{{workflow.parameters.nemesis}}"
                  - name: run-time
                    value: "{{workflow.parameters.run-time}}"
                  - name: tikv-config
                    value: "{{workflow.parameters.tikv-config}}"
                  - name: cdc_hub
                    value: "{{workflow.parameters.cdc_hub}}"
                  - name: cdc_repository
                    value: "{{workflow.parameters.cdc_repository}}"
                  - name: cdc_version
                    value: "{{workflow.parameters.cdc_version}}"
                  - name: cdc_enable-kafka
                    value: "{{workflow.parameters.cdc_enable-kafka}}"
                  - name: cdc_kafka-consumer-image
                    value: "{{workflow.parameters.cdc_kafka-consumer-image}}"
                  - name: abtest_general-log
                    value: "{{workflow.parameters.abtest_general-log}}"
                  - name: binlog_sync-timeout
                    value: "{{workflow.parameters.binlog_sync-timeout}}"
                  - name: abtest_concurrency
                    value: "{{workflow.parameters.abtest_concurrency}}"
                  - name: loki-addr
                    value: "{{workflow.parameters.loki-addr}}"
                  - name: loki-username
                    value: "{{workflow.parameters.loki-username}}"
                  - name: loki-password
                    value: "{{workflow.parameters.loki-password}}"
