metadata:
  name: tipocket-vbank
spec:
  schedule: "0 4 * * *"
  concurrencyPolicy: "Forbid"
  timezone: "Asia/Shanghai"
  startingDeadlineSeconds: 0
  workflowSpec:
    entrypoint: call-tipocket-vbank
    arguments:
      parameters:
        - name: ns
          value: tipocket-vbank
        - name: purge
          value: "true"
        - name: repository
          value: pingcap
        - name: image_version
          value: nightly
        - name: storage_class
          value: gp2
        - name: nemesis
          value: "random_kill,kill_pd_leader_5min,partition_one,subcritical_skews,big_skews,shuffle-leader-scheduler,shuffle-region-scheduler,random-merge-scheduler"
        - name: client
          value: "5"
        - name: request_count
          value: "20000"
        - name: round
          value: "100"
        - name: loki-addr
          value: "http://gateway.loki.svc"
        - name: loki-username
          value: "loki"
        - name: loki-password
          value: "admin"
    templates:
      - name: call-tipocket-vbank
        steps:
          - - name: call-tipocket-vbank
              templateRef:
                name: tipocket-vbank
                template: tipocket-vbank
              arguments:
                parameters:
                  - name: ns
                    value: "{{workflow.parameters.ns}}"
                  - name: purge
                    value: "{{workflow.parameters.purge}}"
                  - name: repository
                    value: "{{workflow.parameters.repository}}"
                  - name: image_version
                    value: "{{workflow.parameters.image_version}}"
                  - name: storage_class
                    value: "{{workflow.parameters.storage_class}}"
                  - name: nemesis
                    value: "{{workflow.parameters.nemesis}}"
                  - name: client
                    value: "{{workflow.parameters.client}}"
                  - name: request_count
                    value: "{{workflow.parameters.request_count}}"
                  - name: round
                    value: "{{workflow.parameters.round}}"
                  - name: loki-addr
                    value: "{{workflow.parameters.loki-addr}}"
                  - name: loki-username
                    value: "{{workflow.parameters.loki-username}}"
                  - name: loki-password
                    value: "{{workflow.parameters.loki-password}}"
