---
apiVersion: v1
kind: ConfigMap
metadata:
  name: chaosfs-tikv
  namespace: chaos-testing
  labels:
    app.kubernetes.io/component: webhook
data:
  chaosfs-tikv: |
    name: chaosfs-tikv
    selector:
      labelSelectors:
        "app.kubernetes.io/component": "tikv"
    template: sidecar-template
    arguments:
      ContainerName: "tikv"
      DataPath: "/var/lib/tikv/data"
      MountPath: "/var/lib/tikv"
      VolumeName: "tikv"
