metadata:
  generateName: tipocket-block-writer-
  namespace: argo
spec:
  entrypoint: call-tipocket-block-writer
  arguments:
    parameters:
      - name: ns
        value: tipocket-block-writer
      - name: purge
        value: "true"
      - name: hub
        value: "hub.pingcap.net"
      - name: repository
        value: qa
      - name: image-version
        value: release-4.0-failpoint
      - name: tidb-image
        value: ""
      - name: tikv-image
        value: ""
      - name: pd-image
        value: ""
      - name: storage-class
        value: sas
      - name: nemesis
        value: ""
      - name: run-time
        value: "60m"
      - name: loki-addr
        value: "http://gateway.loki.svc"
      - name: loki-username
        value: "loki"
      - name: loki-password
        value: "admin"
  templates:
    - name: call-tipocket-block-writer
      steps:
        - - name: call-tipocket-block-writer
            templateRef:
              name: tipocket-block-writer
              template: tipocket-block-writer
            arguments:
              parameters:
                - name: ns
                  value: "{{workflow.parameters.ns}}"
                - name: purge
                  value: "{{workflow.parameters.purge}}"
                - name: hub
                  value: "{{workflow.parameters.hub}}"
                - name: repository
                  value: "{{workflow.parameters.repository}}"
                - name: image-version
                  value: "{{workflow.parameters.image-version}}"
                - name: tidb-image
                  value: "{{workflow.parameters.tidb-image}}"
                - name: tikv-image
                  value: "{{workflow.parameters.tikv-image}}"
                - name: pd-image
                  value: "{{workflow.parameters.pd-image}}"
                - name: storage-class
                  value: "{{workflow.parameters.storage-class}}"
                - name: nemesis
                  value: "{{workflow.parameters.nemesis}}"
                - name: run-time
                  value: "{{workflow.parameters.run-time}}"
                - name: loki-addr
                  value: "{{workflow.parameters.loki-addr}}"
                - name: loki-username
                  value: "{{workflow.parameters.loki-username}}"
                - name: loki-password
                  value: "{{workflow.parameters.loki-password}}"
