metadata:
  generateName: tipocket-region-available-
  namespace: argo
spec:
  entrypoint: call-tipocket-region-available
  arguments:
    parameters:
      - name: ns
        value: tipocket-region-available
      - name: purge
        value: "true"
      - name: hub
        value: "hub.pingcap.net"
      - name: repository
        value: qa
      - name: image-version
        value: release-4.0-failpoint
      - name: tidb-image
        value: ""
      - name: tikv-image
        value: ""
      - name: pd-image
        value: ""
      - name: storage-class
        value: local-path
      - name: nemesis
        value: ""
      - name: run-time
        value: "4h"
      - name: loki-addr
        value: ""
      - name: loki-username
        value: ""
      - name: loki-password
        value: ""
      - name: matrix-config
        value: ""
      - name: matrix-tidb
        value: "tidb.toml"
      - name: matrix-tikv
        value: "tikv.toml"
      - name: matrix-pd
        value: "pd.toml"
      - name: matrix-sql
        value: "mysql-system-vars.sql,tidb-system-vars.sql"
  templates:
    - name: call-tipocket-region-available
      steps:
        - - name: call-tipocket-region-available
            templateRef:
              name: tipocket-region-available
              template: tipocket-region-available
            arguments:
              parameters:
                - name: ns
                  value: "{{workflow.parameters.ns}}"
                - name: purge
                  value: "{{workflow.parameters.purge}}"
                - name: hub
                  value: "{{workflow.parameters.hub}}"
                - name: repository
                  value: "{{workflow.parameters.repository}}"
                - name: image-version
                  value: "{{workflow.parameters.image-version}}"
                - name: tidb-image
                  value: "{{workflow.parameters.tidb-image}}"
                - name: tikv-image
                  value: "{{workflow.parameters.tikv-image}}"
                - name: pd-image
                  value: "{{workflow.parameters.pd-image}}"
                - name: storage-class
                  value: "{{workflow.parameters.storage-class}}"
                - name: nemesis
                  value: "{{workflow.parameters.nemesis}}"
                - name: run-time
                  value: "{{workflow.parameters.run-time}}"
                - name: loki-addr
                  value: "{{workflow.parameters.loki-addr}}"
                - name: loki-username
                  value: "{{workflow.parameters.loki-username}}"
                - name: loki-password
                  value: "{{workflow.parameters.loki-password}}"
                - name: matrix-config
                  value: "{{workflow.parameters.matrix-config}}"
                - name: matrix-tidb
                  value: "{{workflow.parameters.matrix-tidb}}"
                - name: matrix-tikv
                  value: "{{workflow.parameters.matrix-tikv}}"
                - name: matrix-pd
                  value: "{{workflow.parameters.matrix-pd}}"
                - name: matrix-sql
                  value: "{{workflow.parameters.matrix-sql}}"
