apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: tipocket-txn-rand-pessimistic-
spec:
  entrypoint: starter
  onExit: delete-ns
  templates:
    - name: starter
      steps:
        - - name: create-ns
            template: create-ns
        - - name: run-tipocket
            template: run-tipocket
    - container:
        command:
          - sh
          - -c
          - |-
            /bin/txn-rand-pessimistic \
            -client=1 \
            -delNS=false \
            -failpoint.tidb= \
            -hub=docker.io \
            -image-version=nightly \
            -namespace={{workflow.name}} \
            -nemesis=random_kill,kill_pd_leader_5min,partition_one,subcritical_skews,big_skews,shuffle-leader-scheduler,shuffle-region-scheduler,random-merge-scheduler \
            -pd-config= \
            -pd-image= \
            -prepare-sql= \
            -purge=false \
            -repository=pingcap \
            -request-count=10000 \
            -round=1 \
            -run-time=100m \
            -storage-class=local-storage \
            -tidb-config= \
            -tidb-image= \
            -tikv-config= \
            -tikv-image= \
            -tikv-replicas=4
        image: hub.pingcap.net/qa/tipocket
        imagePullPolicy: Always
        name: tipocket
        workingDir: /logs
      name: run-tipocket
      outputs:
        artifacts:
          - archiveLogs: true
            name: case-logs
            path: /logs
          - archiveLogs: true
            name: tidb-logs
            path: /var/run/tipocket-logs
    - name: create-ns
      resource:
        action: create
        manifest: |
          apiVersion: v1
          kind: Namespace
          metadata:
            name: {{workflow.name}}
        successCondition: status.phase = Active
    - name: delete-ns
      resource:
        action: delete
        manifest: |
          apiVersion: v1
          kind: Namespace
          metadata:
            name: {{workflow.name}}
