apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: tipocket-list-append-
spec:
  entrypoint: starter
  onExit: delete-ns
  templates:
    - name: starter
      steps:
        - - name: create-ns
            template: create-ns
        - - name: run-tipocket
            template: run-tipocket
    - container:
        command:
          - sh
          - -c
          - |-
            /bin/append \
            -table-count=7 \
            -read-lock="FOR UPDATE" \
            -txn-mode=pessimistic \
            -namespace={{workflow.name}} \
            -purge=false \
            -hub=docker.io \
            -repository=pingcap \
            -image-version=nightly \
            -tidb-image= \
            -tikv-image= \
            -pd-image= \
            -storage-class=local-storage \
            -nemesis=random_kill,kill_pd_leader_5min,partition_one,subcritical_skews,big_skews,shuffle-leader-scheduler,shuffle-region-scheduler,random-merge-scheduler \
            -client=1 \
            -request-count=10000 \
            -round=1 \
            -tidb-config= \
            -tikv-config= \
            -pd-config= \
            -delNS=true
        image: hub.pingcap.net/mahjonp/tipocket
        imagePullPolicy: Always
        name: tipocket
      name: run-tipocket
    - name: create-ns
      resource:
        action: create
        manifest: |
          apiVersion: v1
          kind: Namespace
          metadata:
            name: {{workflow.name}}
        successCondition: status.phase = Active
    - name: delete-ns
      resource:
        action: delete
        manifest: |
          apiVersion: v1
          kind: Namespace
          metadata:
            name: {{workflow.name}}
