metadata:
  generateName: plan-cache-abtest-
  namespace: argo
spec:
  entrypoint: call-tipocket-abtest
  onExit: call-export-logs
  templates:
    - name: call-export-logs
      steps:
        - - name: call-export-logs
            templateRef:
              name: export-logs
              template: export-logs
            arguments:
              parameters:
                - name: ns
                  value: tipocket-abtest
    - name: call-tipocket-abtest
      steps:
        - - name: call-tipocket-abtest
            templateRef:
              name: tipocket-abtest
              template: tipocket-abtest
            arguments:
              parameters:
                - name: ns
                  value: tipocket-ab-plan-cache
                - name: purge
                  value: "true"
                - name: image_version
                  value: release-4.0-nightly
                - name: storage_class
                  value: pd-ssd
                - name: abtest_version
                  value: release-4.0-nightly
                - name: nemesis
                  value: ""
                - name: tidb_config
                  value: "/config/tidb/prepared-plan-cache.toml"
                - name: tikv_config
                  value: ""
                - name: pd_config
                  value: ""
                - name: abtest_tidb_config
                  value: "/config/tidb/prepared-plan-cache-false.toml"
                - name: abtest_tikv_config
                  value: ""
                - name: abtest_pd_config
                  value: ""

