metadata:
  generateName: tipocket-bank-
  namespace: argo
spec:
  entrypoint: call-tipocket-bank
  templates:
    - name: call-tipocket-bank
      steps:
        - - name: call-tipocket-bank
            templateRef:
              name: tipocket-bank
              template: tipocket-bank
            arguments:
              parameters:
                - name: ns
                  value: tipocket-bank
                - name: purge
                  value: "true"
                - name: image_version
                  value: nightly
                - name: storage_class
                  value: pd-ssd
                - name: nemesis
                  value: random_kill,kill_pd_leader_5min,partition_one,subcritical_skews,big_skews,shuffle-leader-scheduler,shuffle-region-scheduler,random-merge-scheduler
                - name: client
                  value: "5"
                - name: request_count
                  value: "20000"
                - name: round
                  value: "100"

