metadata:
  generateName: tipocket-bank2-replica-read-
  namespace: argo
spec:
  entrypoint: call-tipocket-scbank2
  arguments:
    parameters:
      - name: ns
        value: tipocket-bank2-replica-read
      - name: purge
        value: "true"
      - name: image-version
        value: nightly
      - name: storage-class
        value: local-path
      - name: run-time
        value: "6h"
      - name: loki-addr
        value: ""
      - name: loki-username
        value: "loki"
      - name: loki-password
        value: "admin"
      - name: tikv-replicas
        value: "5"
      - name: tidb-replica-read
        value: "leader-and-follower"
  templates:
    - name: call-tipocket-scbank2
      steps:
        - - name: call-tipocket-scbank2
            templateRef:
              name: tipocket-scbank2
              template: tipocket-scbank2
            arguments:
              parameters:
                - name: ns
                  value: "{{workflow.parameters.ns}}"
                - name: purge
                  value: "{{workflow.parameters.purge}}"
                - name: image-version
                  value: "{{workflow.parameters.image-version}}"
                - name: storage-class
                  value: "{{workflow.parameters.storage-class}}"
                - name: run-time
                  value: "{{workflow.parameters.run-time}}"
                - name: loki-addr
                  value: "{{workflow.parameters.loki-addr}}"
                - name: loki-username
                  value: "{{workflow.parameters.loki-username}}"
                - name: loki-password
                  value: "{{workflow.parameters.loki-password}}"
                - name: tidb-replica-read
                  value: "{{workflow.parameters.tidb-replica-read}}"
