metadata:
  generateName: tipocket-binlog-
  namespace: argo
spec:
  entrypoint: call-tipocket-binlog
  arguments:
    parameters:
      - name: ns
        value: tipocket-binlog
      - name: purge
        value: "true"
      - name: image_version
        value: release-4.0-nightly
      - name: storage_class
        value: gp2
      - name: nemesis
        value: ""
      - name: run_time
        value: "60m"
      - name: relay_log
        value: "true"
      - name: abtest_general_log
        value: "true"
      - name: binlog_sync_timeout
        value: "1h"
      - name: abtest_concurrency
        value: "3"
      - name: loki-addr
        value: "http://gateway.loki.svc"
      - name: loki-username
        value: "loki"
      - name: loki-password
        value: "admin"
  templates:
    - name: call-tipocket-binlog
      steps:
        - - name: call-tipocket-binlog
            templateRef:
              name: tipocket-binlog
              template: tipocket-binlog
            arguments:
              parameters:
                - name: ns
                  value: "{{workflow.parameters.ns}}"
                - name: purge
                  value: "{{workflow.parameters.purge}}"
                - name: image_version
                  value: "{{workflow.parameters.image_version}}"
                - name: storage_class
                  value: "{{workflow.parameters.storage_class}}"
                - name: nemesis
                  value: "{{workflow.parameters.nemesis}}"
                - name: run_time
                  value: "{{workflow.parameters.run_time}}"
                - name: relay_log
                  value: "{{workflow.parameters.relay_log}}"
                - name: abtest_general_log
                  value: "{{workflow.parameters.abtest_general_log}}"
                - name: binlog_sync_timeout
                  value: "{{workflow.parameters.binlog_sync_timeout}}"
                - name: abtest_concurrency
                  value: "{{workflow.parameters.abtest_concurrency}}"
                - name: loki-addr
                  value: "{{workflow.parameters.loki-addr}}"
                - name: loki-username
                  value: "{{workflow.parameters.loki-username}}"
                - name: loki-password
                  value: "{{workflow.parameters.loki-password}}"
