metadata:
  generateName: tipocket-block-writer-
  namespace: argo
spec:
  entrypoint: call-tipocket-block-writer
  arguments:
    parameters:
      - name: ns
        value: tipocket-block-writer
      - name: purge
        value: "true"
      - name: image-version
        value: release-4.0-nightly
      - name: storage-class
        value: gp2
      - name: nemesis
        value: ""
      - name: run-time
        value: "60m"
      - name: loki-addr
        value: "http://gateway.loki.svc"
      - name: loki-username
        value: "loki"
      - name: loki-password
        value: "admin"
  templates:
    - name: call-tipocket-block-writer
      steps:
        - - name: call-tipocket-block-writer
            templateRef:
              name: tipocket-block-writer
              template: tipocket-block-writer
            arguments:
              parameters:
                - name: ns
                  value: "{{workflow.parameters.ns}}"
                - name: purge
                  value: "{{workflow.parameters.purge}}"
                - name: image-version
                  value: "{{workflow.parameters.image-version}}"
                - name: storage-class
                  value: "{{workflow.parameters.storage-class}}"
                - name: nemesis
                  value: "{{workflow.parameters.nemesis}}"
                - name: run-time
                  value: "{{workflow.parameters.run-time}}"
                - name: loki-addr
                  value: "{{workflow.parameters.loki-addr}}"
                - name: loki-username
                  value: "{{workflow.parameters.loki-username}}"
                - name: loki-password
                  value: "{{workflow.parameters.loki-password}}"
