metadata:
  generateName: tipocket-block-writer-
  namespace: argo
spec:
  entrypoint: call-tipocket-block-writer
  onExit: call-export-logs
  arguments:
    parameters:
      - name: ns
        value: tipocket-block-writer
      - name: purge
        value: "true"
      - name: image_version
        value: release-4.0-nightly
      - name: storage_class
        value: pd-ssd
      - name: nemesis
        value: ""
      - name: run_time
        value: "60m"
  templates:
    - name: call-export-logs
      steps:
        - - name: call-export-logs
            templateRef:
              name: export-logs
              template: export-logs
            arguments:
              parameters:
                - name: ns
                  value: "{{workflow.parameters.ns}}"
    - name: call-tipocket-block-writer
      steps:
        - - name: call-tipocket-block-writer
            templateRef:
              name: tipocket-block-writer
              template: tipocket-block-writer
            arguments:
              parameters:
                - name: ns
                  value: "{{workflow.parameters.ns}}"
                - name: purge
                  value: "{{workflow.parameters.purge}}"
                - name: image_version
                  value: "{{workflow.parameters.image_version}}"
                - name: storage_class
                  value: "{{workflow.parameters.storage_class}}"
                - name: nemesis
                  value: "{{workflow.parameters.nemesis}}"
                - name: run_time
                  value: "{{workflow.parameters.run_time}}"
