metadata:
  generateName: tipocket-cdc-
  namespace: argo
spec:
  entrypoint: call-tipocket-cdc
  onExit: call-export-logs
  arguments:
    parameters:
        - name: ns
          value: tipocket-cdc
        - name: purge
          value: "false"
        - name: image_version
          value: release-4.0-nightly
        - name: storage_class
          value: pd-ssd
        - name: nemesis
          value: ""
        - name: run_time
          value: "60m"
        - name: cdc_hub
          default: "hub.pingcap.net"
        - name: cdc_repository
          default: "qa"
        - name: cdc_version
          default: "master"
  templates:
    - name: call-export-logs
      steps:
        - - name: call-export-logs
            templateRef:
              name: export-logs
              template: export-logs
            arguments:
              parameters:
                - name: ns
                  value: "{{workflow.parameters.ns}}"
    - name: call-tipocket-cdc
      steps:
        - - name: call-tipocket-cdc
            templateRef:
              name: tipocket-cdc
              template: tipocket-cdc
            arguments:
              parameters:
                - name: ns
                  value: "{{workflow.parameters.ns}}"
                - name: purge
                  value: "{{workflow.parameters.purge}}"
                - name: image_version
                  value: "{{workflow.parameters.image_version}}"
                - name: storage_class
                  value: "{{workflow.parameters.storage_class}}"
                - name: nemesis
                  value: "{{workflow.parameters.nemesis}}"
                - name: run_time
                  value: "{{workflow.parameters.run_time}}"
                - name: cdc_hub
                  value: "{{workflow.parameters.cdc_hub}}"
                - name: cdc_repository
                  value: "{{workflow.parameters.cdc_repository}}"
                - name: cdc_version
                  value: "{{workflow.parameters.cdc_version}}"
