metadata:
  generateName: tipocket-cdc-
  namespace: argo
spec:
  entrypoint: call-tipocket-cdc
  onExit: call-export-logs
  arguments:
    parameters:
      - name: ns
        value: tipocket-cdc
      - name: purge
        value: "true"
      - name: image_version
        value: release-4.0-nightly
      - name: tidb_image
        value: ""
      - name: tikv_image
        value: ""
      - name: pd_image
        value: ""
      - name: storage_class
        value: pd-ssd
      - name: nemesis
        value: ""
      - name: run_time
        value: "60m"
      - name: tikv_config
        value: ""
      - name: cdc_hub
        value: "docker.io"
      - name: cdc_repository
        value: "pingcap"
      - name: cdc_version
        value: "nightly"
      - name: abtest_general_log
        value: "true"
      - name: binlog_sync_timeout
        value: "1h"
      - name: abtest_concurrency
        value: "3"
  templates:
    - name: call-export-logs
      steps:
        - - name: call-export-logs
            templateRef:
              name: export-logs
              template: export-logs
            arguments:
              parameters:
                - name: ns
                  value: "{{workflow.parameters.ns}}"
    - name: call-tipocket-cdc
      steps:
        - - name: call-tipocket-cdc
            templateRef:
              name: tipocket-cdc
              template: tipocket-cdc
            arguments:
              parameters:
                - name: ns
                  value: "{{workflow.parameters.ns}}"
                - name: purge
                  value: "{{workflow.parameters.purge}}"
                - name: image_version
                  value: "{{workflow.parameters.image_version}}"
                - name: tidb_image
                  value: "{{workflow.parameters.tidb_image}}"
                - name: tikv_image
                  value: "{{workflow.parameters.tikv_image}}"
                - name: pd_image
                  value: "{{workflow.parameters.pd_image}}"
                - name: storage_class
                  value: "{{workflow.parameters.storage_class}}"
                - name: nemesis
                  value: "{{workflow.parameters.nemesis}}"
                - name: run_time
                  value: "{{workflow.parameters.run_time}}"
                - name: tikv_config
                  value: "{{workflow.parameters.tikv_config}}"
                - name: cdc_hub
                  value: "{{workflow.parameters.cdc_hub}}"
                - name: cdc_repository
                  value: "{{workflow.parameters.cdc_repository}}"
                - name: cdc_version
                  value: "{{workflow.parameters.cdc_version}}"
                - name: abtest_general_log
                  value: "{{workflow.parameters.abtest_general_log}}"
                - name: binlog_sync_timeout
                  value: "{{workflow.parameters.binlog_sync_timeout}}"
                - name: abtest_concurrency
                  value: "{{workflow.parameters.abtest_concurrency}}"

