metadata:
  generateName: tipocket-dm-
  namespace: argo
spec:
  entrypoint: call-tipocket-dm
  arguments:
    parameters:
      - name: ns
        value: tipocket-dm
      - name: hub
        value: "docker.io"
      - name: repository
        value: "pingcap"
      - name: image_version
        value: nightly
      - name: tidb_image
        value: ""
      - name: tikv_image
        value: ""
      - name: pd_image
        value: ""
      - name: storage_class
        value: gp2
      - name: nemesis
        value: ""
      - name: run_time
        value: "12h"
      - name: loki-addr
        value: "http://gateway.loki.svc"
      - name: loki-username
        value: "loki"
      - name: loki-password
        value: "admin"
      - name: dm-mysql-version
        value: "5.7"
      - name: dm-mysql-storage-size
        value: "10Gi"
      - name: dm-mysql-enable-binlog
        value: true
      - name: dm-mysql-enable-gtid
        value: true
      - name: dm-version
        value: "nightly"
      - name: dm-master-replicas
        value: 3
      - name: dm-worker-replicas
        value: 3
  templates:
    - name: call-tipocket-dm
      steps:
        - - name: call-tipocket-dm
            templateRef:
              name: tipocket-dm
              template: tipocket-dm
            arguments:
              parameters:
                - name: ns
                  value: "{{workflow.parameters.ns}}"
                - name: hub
                  value: "{{workflow.parameters.hub}}"
                - name: repository
                  value: "{{workflow.parameters.repository}}"
                - name: image_version
                  value: "{{workflow.parameters.image_version}}"
                - name: tidb_image
                  value: "{{workflow.parameters.tidb_image}}"
                - name: tikv_image
                  value: "{{workflow.parameters.tikv_image}}"
                - name: pd_image
                  value: "{{workflow.parameters.pd_image}}"
                - name: storage_class
                  value: "{{workflow.parameters.storage_class}}"
                - name: nemesis
                  value: "{{workflow.parameters.nemesis}}"
                - name: run_time
                  value: "{{workflow.parameters.run_time}}"
                - name: loki-addr
                  value: "{{workflow.parameters.loki-addr}}"
                - name: loki-username
                  value: "{{workflow.parameters.loki-username}}"
                - name: loki-password
                  value: "{{workflow.parameters.loki-password}}"
                - name: dm-mysql-version
                  value: "{{workflow.parameters.dm-mysql-version}}"
                - name: dm-mysql-storage-size
                  value: "{{workflow.parameters.dm-mysql-storage-size}}"
                - name: dm-mysql-enable-binlog
                  value: "{{workflow.parameters.dm-mysql-enable-binlog}}"
                - name: dm-mysql-enable-gtid
                  value: "{{workflow.parameters.dm-mysql-enable-gtid}}"
                - name: dm-version
                  value: "{{workflow.parameters.dm-version}}"
                - name: dm-master-replicas
                  value: "{{workflow.parameters.dm-master-replicas}}"
                - name: dm-worker-replicas
                  value: "{{workflow.parameters.dm-worker-replicas}}"
