metadata:
  generateName: tipocket-dm-
  namespace: argo
spec:
  entrypoint: call-tipocket-dm
  arguments:
    parameters:
      - name: ns
        value: tipocket-dm
      - name: hub
        value: "docker.io"
      - name: repository
        value: "pingcap"
      - name: image-version
        value: nightly
      - name: tidb-image
        value: ""
      - name: tikv-image
        value: ""
      - name: pd-image
        value: ""
      - name: storage-class
        value: local-path
      - name: nemesis
        value: ""
      - name: run-time
        value: "12h"
      - name: loki-addr
        value: ""
      - name: loki-username
        value: "loki"
      - name: loki-password
        value: "admin"
      - name: dm-mysql-version
        value: "5.7"
      - name: dm-mysql-storage-size
        value: "10Gi"
      - name: dm-mysql-enable-binlog
        value: true
      - name: dm-mysql-enable-gtid
        value: true
      - name: dm-version
        value: "nightly"
      - name: dm-master-replicas
        value: 3
      - name: dm-worker-replicas
        value: 3
  templates:
    - name: call-tipocket-dm
      steps:
        - - name: call-tipocket-dm
            templateRef:
              name: tipocket-dm
              template: tipocket-dm
            arguments:
              parameters:
                - name: ns
                  value: "{{workflow.parameters.ns}}"
                - name: hub
                  value: "{{workflow.parameters.hub}}"
                - name: repository
                  value: "{{workflow.parameters.repository}}"
                - name: image-version
                  value: "{{workflow.parameters.image-version}}"
                - name: tidb-image
                  value: "{{workflow.parameters.tidb-image}}"
                - name: tikv-image
                  value: "{{workflow.parameters.tikv-image}}"
                - name: pd-image
                  value: "{{workflow.parameters.pd-image}}"
                - name: storage-class
                  value: "{{workflow.parameters.storage-class}}"
                - name: nemesis
                  value: "{{workflow.parameters.nemesis}}"
                - name: run-time
                  value: "{{workflow.parameters.run-time}}"
                - name: loki-addr
                  value: "{{workflow.parameters.loki-addr}}"
                - name: loki-username
                  value: "{{workflow.parameters.loki-username}}"
                - name: loki-password
                  value: "{{workflow.parameters.loki-password}}"
                - name: dm-mysql-version
                  value: "{{workflow.parameters.dm-mysql-version}}"
                - name: dm-mysql-storage-size
                  value: "{{workflow.parameters.dm-mysql-storage-size}}"
                - name: dm-mysql-enable-binlog
                  value: "{{workflow.parameters.dm-mysql-enable-binlog}}"
                - name: dm-mysql-enable-gtid
                  value: "{{workflow.parameters.dm-mysql-enable-gtid}}"
                - name: dm-version
                  value: "{{workflow.parameters.dm-version}}"
                - name: dm-master-replicas
                  value: "{{workflow.parameters.dm-master-replicas}}"
                - name: dm-worker-replicas
                  value: "{{workflow.parameters.dm-worker-replicas}}"
