metadata:
  generateName: tipocket-follower-read-
  namespace: argo
spec:
  entrypoint: call-tipocket-follower-read
  arguments:
    parameters:
      - name: ns
        value: tipocket-follower-read
      - name: purge
        value: "true"
      - name: repository
        value: pingcap
      - name: image_version
        value: nightly
      - name: storage_class
        value: gp2
      - name: nemesis
        value: ""
      - name: run_time
        value: "6h"
      - name: loki-username
        value: loki
      - name: loki-password
        value: admin
      - name: loki-addr
        value: "http://gateway.loki.svc"
  templates:
    - name: call-tipocket-follower-read
      steps:
        - - name: call-tipocket-follower-read
            templateRef:
              name: tipocket-follower-read
              template: tipocket-follower-read
            arguments:
              parameters:
                - name: ns
                  value: "{{workflow.parameters.ns}}"
                - name: purge
                  value: "{{workflow.parameters.purge}}"
                - name: repository
                  value: "{{workflow.parameters.repository}}"
                - name: image_version
                  value: "{{workflow.parameters.image_version}}"
                - name: storage_class
                  value: "{{workflow.parameters.storage_class}}"
                - name: nemesis
                  value: "{{workflow.parameters.nemesis}}"
                - name: run_time
                  value: "{{workflow.parameters.run_time}}"
                - name: loki-addr
                  value: "{{workflow.parameters.loki-addr}}"
                - name: loki-username
                  value: "{{workflow.parameters.loki-username}}"
                - name: loki-password
                  value: "{{workflow.parameters.loki-password}}"