metadata:
  generateName: tipocket-ledger-
  namespace: argo
spec:
  entrypoint: call-tipocket-ledger
  templates:
    - name: call-tipocket-ledger
      steps:
        - - name: call-tipocket-ledger
            templateRef:
              name: tipocket-ledger
              template: tipocket-ledger
            arguments:
              parameters:
                - name: ns
                  value: tipocket-ledger
                - name: purge
                  value: "true"
                - name: image_version
                  value: nightly
                - name: storage_class
                  value: pd-ssd
                - name: nemesis
                  value: ""
                - name: run_time
                  value: "60m"
