metadata:
  generateName: tipocket-rawkv-linearizability-
  namespace: argo
spec:
  entrypoint: call-tipocket-rawkv-linearizability
  arguments:
    parameters:
      - name: ns
        value: tipocket-rawkv-linearizability
      - name: purge
        value: "true"
      - name: image-version
        value: release-4.0-nightly
      - name: storage-class
        value: pd-ssd
      - name: nemesis
        value: "partition_one,subcritical_skews,big_skews,shuffle-leader-scheduler,shuffle-region-scheduler,random-merge-scheduler"
      - name: client
        value: "5"
      - name: request-count
        value: "20000"
      - name: round
        value: "100"
      - name: loki-addr
        value: "http://gateway.loki.svc"
      - name: loki-username
        value: "loki"
      - name: loki-password
        value: "admin"
  templates:
    - name: call-tipocket-rawkv-linearizability
      steps:
        - - name: call-tipocket-rawkv-linearizability
            templateRef:
              name: tipocket-rawkv-linearizability
              template: tipocket-rawkv-linearizability
            arguments:
              parameters:
                - name: ns
                  value: "{{workflow.parameters.ns}}"
                - name: purge
                  value: "{{workflow.parameters.purge}}"
                - name: image-version
                  value: "{{workflow.parameters.image-version}}"
                - name: storage-class
                  value: "{{workflow.parameters.storage-class}}"
                - name: nemesis
                  value: "{{workflow.parameters.nemesis}}"
                - name: client
                  value: "{{workflow.parameters.client}}"
                - name: request-count
                  value: "{{workflow.parameters.request-count}}"
                - name: round
                  value: "{{workflow.parameters.round}}"
                - name: loki-addr
                  value: "{{workflow.parameters.loki-addr}}"
                - name: loki-username
                  value: "{{workflow.parameters.loki-username}}"
                - name: loki-password
                  value: "{{workflow.parameters.loki-password}}"