metadata:
  generateName: tipocket-read-stress-
  namespace: argo
spec:
  entrypoint: call-tipocket-read-stress
  onExit: call-export-logs
  arguments:
    parameters:
      - name: ns
        value: tipocket-read-stress-unify-all
      - name: purge
        value: "true"
      - name: image_version
        value: nightly
      - name: nemesis
        value: ""
      - name: run_time
        value: "6h"
      - name: tikv_config
        value: "/config/tikv/unify-all-read-pools.toml"
  templates:
    - name: call-export-logs
      steps:
        - - name: call-export-logs
            templateRef:
              name: export-logs
              template: export-logs
            arguments:
              parameters:
                - name: ns
                  value: tipocket-read-stress
    - name: call-tipocket-read-stress
      steps:
        - - name: call-tipocket-read-stress
            templateRef:
              name: tipocket-read-stress
              template: tipocket-read-stress
            arguments:
              parameters:
                - name: ns
                  value: "{{workflow.parameters.ns}}"
                - name: purge
                  value: "{{workflow.parameters.purge}}"
                - name: image_version
                  value: "{{workflow.parameters.image_version}}"
                - name: storage_class
                  value: "{{workflow.parameters.storage_class}}"
                - name: nemesis
                  value: "{{workflow.parameters.nemesis}}"
                - name: run_time
                  value: "{{workflow.parameters.run_time}}"
