metadata:
  generateName: tipocket-read-stress-
  namespace: argo
spec:
  entrypoint: call-tipocket-read-stress
  arguments:
    parameters:
      - name: ns
        value: tipocket-read-stress-unify-all
      - name: purge
        value: "true"
      - name: repository
        value: pingcap
      - name: image-version
        value: nightly
      - name: storage-class
        value: local-path
      - name: nemesis
        value: ""
      - name: run-time
        value: "6h"
      - name: tikv-config
        value: "/config/tikv/unify-all-read-pools.toml"
      - name: loki-addr
        value: ""
      - name: loki-username
        value: loki
      - name: loki-password
        value: admin
      - name: loki-addr
        value: ""
      - name: loki-username
        value: "loki"
      - name: loki-password
        value: "admin"
  templates:
    - name: call-tipocket-read-stress
      steps:
        - - name: call-tipocket-read-stress
            templateRef:
              name: tipocket-read-stress
              template: tipocket-read-stress
            arguments:
              parameters:
                - name: ns
                  value: "{{workflow.parameters.ns}}"
                - name: purge
                  value: "{{workflow.parameters.purge}}"
                - name: repository
                  value: "{{workflow.parameters.repository}}"
                - name: image-version
                  value: "{{workflow.parameters.image-version}}"
                - name: storage-class
                  value: "{{workflow.parameters.storage-class}}"
                - name: nemesis
                  value: "{{workflow.parameters.nemesis}}"
                - name: run-time
                  value: "{{workflow.parameters.run-time}}"
                - name: loki-addr
                  value: "{{workflow.parameters.loki-addr}}"
                - name: loki-username
                  value: "{{workflow.parameters.loki-username}}"
                - name: loki-password
                  value: "{{workflow.parameters.loki-password}}"
                - name: tikv-config
                  value: "{{workflow.parameters.tikv-config}}"
                - name: loki-addr
                  value: "{{workflow.parameters.loki-addr}}"
                - name: loki-username
                  value: "{{workflow.parameters.loki-username}}"
                - name: loki-password
                  value: "{{workflow.parameters.loki-password}}"
