metadata:
  generateName: tipocket-region-available-
  namespace: argo
spec:
  entrypoint: call-tipocket-region-available
  arguments:
    parameters:
      - name: ns
        value: tipocket-region-available
      - name: purge
        value: "true"
      - name: image_version
        value: nightly
      - name: storage_class
        value: local-storage
      - name: nemesis
        value: ""
      - name: run_time
        value: "4h"
      - name: loki-addr
        value: "http://loki.loki.svc"
      - name: loki-username
        value: ""
      - name: loki-password
        value: ""
  templates:
    - name: call-tipocket-region-available
      steps:
        - - name: call-tipocket-region-available
            templateRef:
              name: tipocket-region-available
              template: tipocket-region-available
            arguments:
              parameters:
                - name: ns
                  value: "{{workflow.parameters.ns}}"
                - name: purge
                  value: "{{workflow.parameters.purge}}"
                - name: image_version
                  value: "{{workflow.parameters.image_version}}"
                - name: storage_class
                  value: "{{workflow.parameters.storage_class}}"
                - name: nemesis
                  value: "{{workflow.parameters.nemesis}}"
                - name: run_time
                  value: "{{workflow.parameters.run_time}}"
                - name: loki-addr
                  value: "{{workflow.parameters.loki-addr}}"
                - name: loki-username
                  value: "{{workflow.parameters.loki-username}}"
                - name: loki-password
                  value: "{{workflow.parameters.loki-password}}"
