metadata:
  generateName: tipocket-resolve-lock-master-
  namespace: argo
spec:
  entrypoint: call-tipocket-resolve-lock
  arguments:
    parameters:
      - name: ns
        value: tipocket-resolve-lock
      - name: purge
        value: "true"
      - name: image-version
        value: nightly
      - name: tidb-image
        value: "hub.pingcap.net/qa/tidb:master-failpoint"
      - name: tikv-image
        value: "hub.pingcap.net/qa/tikv:master-failpoint"
      - name: pd-image
        value: "hub.pingcap.net/qa/pd:master-failpoint"
      - name: storage-class
        value: sas
      - name: nemesis
        value: "shuffle-leader-scheduler,shuffle-region-scheduler,random-merge-scheduler,scaling"
      - name: run-time
        value: "6h"
      - name: tikv-replicas
        value: "3"
      - name: loki-addr
        value: "http://gateway.loki.svc"
      - name: loki-username
        value: "loki"
      - name: loki-password
        value: "admin"
  templates:
    - name: call-tipocket-resolve-lock
      steps:
        - - name: call-tipocket-resolve-lock
            templateRef:
              name: tipocket-resolve-lock
              template: tipocket-resolve-lock
            arguments:
              parameters:
                - name: ns
                  value: "{{workflow.parameters.ns}}"
                - name: purge
                  value: "{{workflow.parameters.purge}}"
                - name: image-version
                  value: "{{workflow.parameters.image-version}}"
                - name: tidb-image
                  value: "{{workflow.parameters.tidb-image}}"
                - name: tikv-image
                  value: "{{workflow.parameters.tikv-image}}"
                - name: pd-image
                  value: "{{workflow.parameters.pd-image}}"
                - name: storage-class
                  value: "{{workflow.parameters.storage-class}}"
                - name: nemesis
                  value: "{{workflow.parameters.nemesis}}"
                - name: run-time
                  value: "{{workflow.parameters.run-time}}"
                - name: loki-addr
                  value: "{{workflow.parameters.loki-addr}}"
                - name: loki-username
                  value: "{{workflow.parameters.loki-username}}"
                - name: loki-password
                  value: "{{workflow.parameters.loki-password}}"
