metadata:
  generateName: tipocket-sqllogic-
  namespace: argo
spec:
  entrypoint: call-tipocket-sqllogic
  onExit: call-export-logs
  templates:
    - name: call-export-logs
      steps:
        - - name: call-export-logs
            templateRef:
              name: export-logs
              template: export-logs
            arguments:
              parameters:
                - name: ns
                  value: tipocket-sqllogic
    - name: call-tipocket-sqllogic
      steps:
        - - name: call-tipocket-sqllogic
            templateRef:
              name: tipocket-sqllogic
              template: tipocket-sqllogic
            arguments:
              parameters:
                - name: ns
                  value: tipocket-sqllogic
                - name: purge
                  value: "true"
                - name: image_version
                  value: nightly
                - name: storage_class
                  value: pd-ssd
