metadata:
    generateName: tipocket-titan-raw-
    namespace: argo
  spec:
    entrypoint: call-tipocket-titan-raw
    arguments:
      parameters:
        - name: ns
          value: tipocket-titan-raw
        - name: purge
          value: "true"
        - name: image-version
          value: release-4.0-nightly
        - name: storage-class
          value: local-path
        - name: nemesis
          value: "short_kill_tikv_1node,mixed_tikv,shuffle-region-scheduler,kill_tikv_1node_5min"
        - name: client
          value: "1"
        - name: loki-addr
          value: ""
        - name: loki-username
          value: "loki"
        - name: loki-password
          value: "admin"
        - name: tikv-config
          value: "/config/tikv/titan-raw.toml"
        - name: tikv-replicas
          value: 5
    templates:
      - name: call-tipocket-titan-raw
        steps:
          - - name: call-tipocket-titan-raw
              templateRef:
                name: titan-raw
                template: titan-raw
              arguments:
                parameters:
                  - name: ns
                    value: "{{workflow.parameters.ns}}"
                  - name: purge
                    value: "{{workflow.parameters.purge}}"
                  - name: image-version
                    value: "{{workflow.parameters.image-version}}"
                  - name: storage-class
                    value: "{{workflow.parameters.storage-class}}"
                  - name: nemesis
                    value: "{{workflow.parameters.nemesis}}"
                  - name: client
                    value: "{{workflow.parameters.client}}"
                  - name: loki-addr
                    value: "{{workflow.parameters.loki-addr}}"
                  - name: loki-username
                    value: "{{workflow.parameters.loki-username}}"
                  - name: loki-password
                    value: "{{workflow.parameters.loki-password}}"
                  - name: tikv-config
                    value: "{{workflow.parameters.tikv-config}}"
                  - name: tikv-replicas
                    value: "{{workflow.parameters.tikv-replicas}}"
  