metadata:
  generateName: tipocket-titan-bank-
  namespace: argo
spec:
  entrypoint: call-tipocket-bank
  arguments:
    parameters:
      - name: ns
        value: tipocket-titan-bank
      - name: purge
        value: "true"
      - name: image-version
        value: release-4.0-nightly
      - name: storage-class
        value: local-path
      - name: nemesis
        value: "short_kill_tikv_1node,mixed_tikv,shuffle-region-scheduler,kill_tikv_1node_5min"
      - name: client
        value: "5"
      - name: request-count
        value: "10000"
      - name: round
        value: "100"
      - name: loki-addr
        value: ""
      - name: loki-username
        value: "loki"
      - name: loki-password
        value: "admin"
      - name: tikv-config
        value: "/config/tikv/titan-bank.toml"
      - name: tikv-replicas
        value: 5
  templates:
    - name: call-tipocket-bank
      steps:
        - - name: call-tipocket-bank
            templateRef:
              name: tipocket-bank
              template: tipocket-bank
            arguments:
              parameters:
                - name: ns
                  value: "{{workflow.parameters.ns}}"
                - name: purge
                  value: "{{workflow.parameters.purge}}"
                - name: image-version
                  value: "{{workflow.parameters.image-version}}"
                - name: storage-class
                  value: "{{workflow.parameters.storage-class}}"
                - name: nemesis
                  value: "{{workflow.parameters.nemesis}}"
                - name: client
                  value: "{{workflow.parameters.client}}"
                - name: request-count
                  value: "{{workflow.parameters.request-count}}"
                - name: round
                  value: "{{workflow.parameters.round}}"
                - name: loki-addr
                  value: "{{workflow.parameters.loki-addr}}"
                - name: loki-username
                  value: "{{workflow.parameters.loki-username}}"
                - name: loki-password
                  value: "{{workflow.parameters.loki-password}}"
                - name: tikv-config
                  value: "{{workflow.parameters.tikv-config}}"
                - name: tikv-replicas
                  value: "{{workflow.parameters.tikv-replicas}}"
