metadata:
  generateName: tipocket-tpcc-
  namespace: argo
spec:
  entrypoint: call-tipocket-tpcc
  templates:
    - name: call-tipocket-tpcc
      steps:
        - - name: call-tipocket-tpcc
            templateRef:
              name: tipocket-tpcc
              template: tipocket-tpcc
            arguments:
              parameters:
                - name: ns
                  value: tipocket-tpcc
                - name: purge
                  value: "true"
                - name: image_version
                  value: nightly
                - name: storage_class
                  value: pd-ssd
                - name: nemesis
                  value: random_kill,kill_pd_leader_5min,partition_one,subcritical_skews,big_skews,shuffle-leader-scheduler,shuffle-region-scheduler,random-merge-scheduler
                - name: client
                  value: "100"
                - name: request_count
                  value: "1000000"
                - name: round
                  value: "10"
