metadata:
  generateName: tipocket-tpcc-
  namespace: argo
spec:
  entrypoint: call-tipocket-tpcc
  onExit: call-export-logs
  arguments:
    parameters:
    - name: ns
      value: tipocket-tpcc
    - name: purge
      value: "true"
    - name: image_version
      value: release-4.0-nightly
    - name: storage_class
      value: pd-ssd
    - name: nemesis
      value: random_kill,kill_pd_leader_5min,partition_one,subcritical_skews,big_skews,shuffle-leader-scheduler,shuffle-region-scheduler,random-merge-scheduler
    - name: client
      value: "100"
    - name: request_count
      value: "1000000"
    - name: round
      value: "10"
  templates:
    - name: call-export-logs
      steps:
        - - name: call-export-logs
            templateRef:
              name: export-logs
              template: export-logs
            arguments:
              parameters:
                - name: ns
                  value: "{{workflow.parameters.ns}}"
    - name: call-tipocket-tpcc
      steps:
        - - name: call-tipocket-tpcc
            templateRef:
              name: tipocket-tpcc
              template: tipocket-tpcc
            arguments:
              parameters:
                - name: ns
                  value: "{{workflow.parameters.ns}}"
                - name: purge
                  value: "{{workflow.parameters.purge}}"
                - name: image_version
                  value: "{{workflow.parameters.image_version}}"
                - name: storage_class
                  value: "{{workflow.parameters.storage_class}}"
                - name: nemesis
                  value: "{{workflow.parameters.nemesis}}"
                - name: client
                  value: "{{workflow.parameters.client}}"
                - name: request_count
                  value: "{{workflow.parameters.request_count}}"
                - name: round
                  value: "{{workflow.parameters.round}}"
