metadata:
  generateName: tipocket-txn-rand-pessimistic-
  namespace: argo
spec:
  entrypoint: call-tipocket-txn-rand-pessimistic
  onExit: call-export-logs
  arguments:
    parameters:
      - name: ns
        value: tipocket-txn-rand-pessimistic
      - name: purge
        value: "true"
      - name: image_version
        value: release-4.0-nightly
      - name: storage_class
        value: gp2
      - name: nemesis
        value: random_kill,kill_pd_leader_5min,partition_one,subcritical_skews,big_skews,shuffle-leader-scheduler,shuffle-region-scheduler,random-merge-scheduler
      - name: run_time
        value: "4h"
  templates:
    - name: call-export-logs
      steps:
        - - name: call-export-logs
            templateRef:
              name: export-logs
              template: export-logs
            arguments:
              parameters:
                - name: ns
                  value: tipocket-txn-rand-pessimistic
    - name: call-tipocket-txn-rand-pessimistic
      steps:
        - - name: call-tipocket-txn-rand-pessimistic
            templateRef:
              name: tipocket-txn-rand-pessimistic
              template: tipocket-txn-rand-pessimistic
            arguments:
              parameters:
                - name: ns
                  value: "{{workflow.parameters.ns}}"
                - name: purge
                  value: "{{workflow.parameters.purge}}"
                - name: image_version
                  value: "{{workflow.parameters.image_version}}"
                - name: storage_class
                  value: "{{workflow.parameters.storage_class}}"
                - name: nemesis
                  value: "{{workflow.parameters.nemesis}}"
                - name: run_time
                  value: "{{workflow.parameters.run_time}}"
